// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: activity.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActBrief.status 状态枚举
type ActStatus int32

const (
	ActStatus_NotStarted   ActStatus = 0 // 未激活/不可用
	ActStatus_Claimable    ActStatus = 1 // 可领奖; 显示红点
	ActStatus_Participable ActStatus = 2 // 可参与/可购买; 不显示红点（前端按活动类型区分展示）
	ActStatus_FullyClaimed ActStatus = 3 // 已完成，已领奖
)

// Enum value maps for ActStatus.
var (
	ActStatus_name = map[int32]string{
		0: "NotStarted",
		1: "Claimable",
		2: "Participable",
		3: "FullyClaimed",
	}
	ActStatus_value = map[string]int32{
		"NotStarted":   0,
		"Claimable":    1,
		"Participable": 2,
		"FullyClaimed": 3,
	}
)

func (x ActStatus) Enum() *ActStatus {
	p := new(ActStatus)
	*p = x
	return p
}

func (x ActStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_proto_enumTypes[0].Descriptor()
}

func (ActStatus) Type() protoreflect.EnumType {
	return &file_activity_proto_enumTypes[0]
}

func (x ActStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActStatus.Descriptor instead.
func (ActStatus) EnumDescriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

// 活动通用请求包装器（客户端调用）
type ActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *anypb.Any             `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityReq) Reset() {
	*x = ActivityReq{}
	mi := &file_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityReq) ProtoMessage() {}

func (x *ActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityReq.ProtoReflect.Descriptor instead.
func (*ActivityReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityReq) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

// 活动通用响应包装器（客户端调用）
type ActivityAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *anypb.Any             `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityAck) Reset() {
	*x = ActivityAck{}
	mi := &file_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAck) ProtoMessage() {}

func (x *ActivityAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAck.ProtoReflect.Descriptor instead.
func (*ActivityAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

// 获取活动列表请求
type ActsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActsListReq) Reset() {
	*x = ActsListReq{}
	mi := &file_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActsListReq) ProtoMessage() {}

func (x *ActsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActsListReq.ProtoReflect.Descriptor instead.
func (*ActsListReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{2}
}

// 获取活动列表响应
type ActsListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedDot        bool                   `protobuf:"varint,1,opt,name=red_dot,json=redDot,proto3" json:"red_dot,omitempty"` // 是否有点红
	Acts          []*ActBrief            `protobuf:"bytes,2,rep,name=acts,proto3" json:"acts,omitempty"`                    // 活动列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActsListAck) Reset() {
	*x = ActsListAck{}
	mi := &file_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActsListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActsListAck) ProtoMessage() {}

func (x *ActsListAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActsListAck.ProtoReflect.Descriptor instead.
func (*ActsListAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{3}
}

func (x *ActsListAck) GetRedDot() bool {
	if x != nil {
		return x.RedDot
	}
	return false
}

func (x *ActsListAck) GetActs() []*ActBrief {
	if x != nil {
		return x.Acts
	}
	return nil
}

// 获取活动详情
type ActPanelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` //活动ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActPanelReq) Reset() {
	*x = ActPanelReq{}
	mi := &file_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActPanelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActPanelReq) ProtoMessage() {}

func (x *ActPanelReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActPanelReq.ProtoReflect.Descriptor instead.
func (*ActPanelReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{4}
}

func (x *ActPanelReq) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

// 获取活动状态响应
type ActPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Ack           *anypb.Any             `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"` // 活动私有数据，客户端直接透传解析
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActPanelAck) Reset() {
	*x = ActPanelAck{}
	mi := &file_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActPanelAck) ProtoMessage() {}

func (x *ActPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActPanelAck.ProtoReflect.Descriptor instead.
func (*ActPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{5}
}

func (x *ActPanelAck) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActPanelAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

// 活动操作请求
type ActRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动ID
	Req           *anypb.Any             `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`                                  // 活动需要的参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRewardReq) Reset() {
	*x = ActRewardReq{}
	mi := &file_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRewardReq) ProtoMessage() {}

func (x *ActRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRewardReq.ProtoReflect.Descriptor instead.
func (*ActRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{6}
}

func (x *ActRewardReq) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActRewardReq) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

// 活动操作响应
type ActRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Ack           *anypb.Any             `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"` // 返回奖励、新余额等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRewardAck) Reset() {
	*x = ActRewardAck{}
	mi := &file_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRewardAck) ProtoMessage() {}

func (x *ActRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRewardAck.ProtoReflect.Descriptor instead.
func (*ActRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{7}
}

func (x *ActRewardAck) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActRewardAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

// 活动列表项
type ActBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 活动名称
	Status        ActStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=cproto.ActStatus" json:"status,omitempty"`
	EndTs         int64                  `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActBrief) Reset() {
	*x = ActBrief{}
	mi := &file_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActBrief) ProtoMessage() {}

func (x *ActBrief) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActBrief.ProtoReflect.Descriptor instead.
func (*ActBrief) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{8}
}

func (x *ActBrief) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActBrief) GetStatus() ActStatus {
	if x != nil {
		return x.Status
	}
	return ActStatus_NotStarted
}

func (x *ActBrief) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

type PurchasePkgAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`                                                // 活动ID
	PkgId         int32                  `protobuf:"varint,2,opt,name=pkg_id,json=pkgId,proto3" json:"pkg_id,omitempty"`                                                               //礼包id
	Items         map[int32]int64        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchasePkgAck) Reset() {
	*x = PurchasePkgAck{}
	mi := &file_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchasePkgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasePkgAck) ProtoMessage() {}

func (x *PurchasePkgAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasePkgAck.ProtoReflect.Descriptor instead.
func (*PurchasePkgAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{9}
}

func (x *PurchasePkgAck) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PurchasePkgAck) GetPkgId() int32 {
	if x != nil {
		return x.PkgId
	}
	return 0
}

func (x *PurchasePkgAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 邀请活动 (invite) =====
type InvitePanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviteCnt     int32                  `protobuf:"varint,2,opt,name=invite_cnt,json=inviteCnt,proto3" json:"invite_cnt,omitempty"`
	Rewards       []*InviteRewardState   `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`
	Users         []*InviteUser          `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePanelAck) Reset() {
	*x = InvitePanelAck{}
	mi := &file_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePanelAck) ProtoMessage() {}

func (x *InvitePanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePanelAck.ProtoReflect.Descriptor instead.
func (*InvitePanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{10}
}

func (x *InvitePanelAck) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *InvitePanelAck) GetInviteCnt() int32 {
	if x != nil {
		return x.InviteCnt
	}
	return 0
}

func (x *InvitePanelAck) GetRewards() []*InviteRewardState {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *InvitePanelAck) GetUsers() []*InviteUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type InviteRewardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Cond          int32                  `protobuf:"varint,2,opt,name=cond,proto3" json:"cond,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	Got           bool                   `protobuf:"varint,4,opt,name=got,proto3" json:"got,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRewardState) Reset() {
	*x = InviteRewardState{}
	mi := &file_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRewardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardState) ProtoMessage() {}

func (x *InviteRewardState) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardState.ProtoReflect.Descriptor instead.
func (*InviteRewardState) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{11}
}

func (x *InviteRewardState) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *InviteRewardState) GetCond() int32 {
	if x != nil {
		return x.Cond
	}
	return 0
}

func (x *InviteRewardState) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *InviteRewardState) GetGot() bool {
	if x != nil {
		return x.Got
	}
	return false
}

func (x *InviteRewardState) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *InviteRewardState) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type InviteUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUser) Reset() {
	*x = InviteUser{}
	mi := &file_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUser) ProtoMessage() {}

func (x *InviteUser) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUser.ProtoReflect.Descriptor instead.
func (*InviteUser) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{12}
}

func (x *InviteUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *InviteUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type InviteRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRewardReq) Reset() {
	*x = InviteRewardReq{}
	mi := &file_activity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardReq) ProtoMessage() {}

func (x *InviteRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardReq.ProtoReflect.Descriptor instead.
func (*InviteRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{13}
}

func (x *InviteRewardReq) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type InviteRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRewardAck) Reset() {
	*x = InviteRewardAck{}
	mi := &file_activity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardAck) ProtoMessage() {}

func (x *InviteRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardAck.ProtoReflect.Descriptor instead.
func (*InviteRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{14}
}

func (x *InviteRewardAck) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *InviteRewardAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 红包活动 (redpacket) =====
type RedpacketPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 状态: 0未激活（可分享)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedpacketPanelAck) Reset() {
	*x = RedpacketPanelAck{}
	mi := &file_activity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedpacketPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedpacketPanelAck) ProtoMessage() {}

func (x *RedpacketPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedpacketPanelAck.ProtoReflect.Descriptor instead.
func (*RedpacketPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{15}
}

func (x *RedpacketPanelAck) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RedpacketRcvPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     string                 `protobuf:"bytes,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"` // 发送人UID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                       // 状态: 0未激活,1-分享领取，2-视频领取，3-已全部领取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedpacketRcvPanelAck) Reset() {
	*x = RedpacketRcvPanelAck{}
	mi := &file_activity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedpacketRcvPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedpacketRcvPanelAck) ProtoMessage() {}

func (x *RedpacketRcvPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedpacketRcvPanelAck.ProtoReflect.Descriptor instead.
func (*RedpacketRcvPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{16}
}

func (x *RedpacketRcvPanelAck) GetSenderUid() string {
	if x != nil {
		return x.SenderUid
	}
	return ""
}

func (x *RedpacketRcvPanelAck) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RedpacketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                        // "panel","share", "link", "video"
	SenderUid     string                 `protobuf:"bytes,2,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"` // 发送人UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedpacketReq) Reset() {
	*x = RedpacketReq{}
	mi := &file_activity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedpacketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedpacketReq) ProtoMessage() {}

func (x *RedpacketReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedpacketReq.ProtoReflect.Descriptor instead.
func (*RedpacketReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{17}
}

func (x *RedpacketReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RedpacketReq) GetSenderUid() string {
	if x != nil {
		return x.SenderUid
	}
	return ""
}

type RedpacketAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     string                 `protobuf:"bytes,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"` // 发送人UID
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedpacketAck) Reset() {
	*x = RedpacketAck{}
	mi := &file_activity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedpacketAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedpacketAck) ProtoMessage() {}

func (x *RedpacketAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedpacketAck.ProtoReflect.Descriptor instead.
func (*RedpacketAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{18}
}

func (x *RedpacketAck) GetSenderUid() string {
	if x != nil {
		return x.SenderUid
	}
	return ""
}

func (x *RedpacketAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RedpacketAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 好运签活动 (lucky) =====
type LuckyPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`                          // 今日已抽签次数: 0-3
	LeftCount     int32                  `protobuf:"varint,2,opt,name=left_count,json=leftCount,proto3" json:"left_count,omitempty"` // 剩余次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyPanelAck) Reset() {
	*x = LuckyPanelAck{}
	mi := &file_activity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyPanelAck) ProtoMessage() {}

func (x *LuckyPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyPanelAck.ProtoReflect.Descriptor instead.
func (*LuckyPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{19}
}

func (x *LuckyPanelAck) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LuckyPanelAck) GetLeftCount() int32 {
	if x != nil {
		return x.LeftCount
	}
	return 0
}

type LuckyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "video" 看广告抽签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyReq) Reset() {
	*x = LuckyReq{}
	mi := &file_activity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyReq) ProtoMessage() {}

func (x *LuckyReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyReq.ProtoReflect.Descriptor instead.
func (*LuckyReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{20}
}

func (x *LuckyReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type LuckyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励物品
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                                                                            // 今日已抽签次数
	LeftCount     int32                  `protobuf:"varint,4,opt,name=left_count,json=leftCount,proto3" json:"left_count,omitempty"`                                                   // 剩余次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyAck) Reset() {
	*x = LuckyAck{}
	mi := &file_activity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyAck) ProtoMessage() {}

func (x *LuckyAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyAck.ProtoReflect.Descriptor instead.
func (*LuckyAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{21}
}

func (x *LuckyAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LuckyAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LuckyAck) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LuckyAck) GetLeftCount() int32 {
	if x != nil {
		return x.LeftCount
	}
	return 0
}

// ===== 注册活动 (register) =====
type RegisterPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0未领取 1普通领取 2看广告翻倍领取
	NormalItems   map[int32]int64        `protobuf:"bytes,2,rep,name=normal_items,json=normalItems,proto3" json:"normal_items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DoubleItems   map[int32]int64        `protobuf:"bytes,3,rep,name=double_items,json=doubleItems,proto3" json:"double_items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPanelAck) Reset() {
	*x = RegisterPanelAck{}
	mi := &file_activity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPanelAck) ProtoMessage() {}

func (x *RegisterPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPanelAck.ProtoReflect.Descriptor instead.
func (*RegisterPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterPanelAck) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegisterPanelAck) GetNormalItems() map[int32]int64 {
	if x != nil {
		return x.NormalItems
	}
	return nil
}

func (x *RegisterPanelAck) GetDoubleItems() map[int32]int64 {
	if x != nil {
		return x.DoubleItems
	}
	return nil
}

type RegisterRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "normal" 或 "video"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRewardReq) Reset() {
	*x = RegisterRewardReq{}
	mi := &file_activity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRewardReq) ProtoMessage() {}

func (x *RegisterRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRewardReq.ProtoReflect.Descriptor instead.
func (*RegisterRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterRewardReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type RegisterRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "normal" 或 "video"
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRewardAck) Reset() {
	*x = RegisterRewardAck{}
	mi := &file_activity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRewardAck) ProtoMessage() {}

func (x *RegisterRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRewardAck.ProtoReflect.Descriptor instead.
func (*RegisterRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterRewardAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RegisterRewardAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 参与活动 (engage) =====
type EngagePanelAck struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Goal          int32                   `protobuf:"varint,1,opt,name=goal,proto3" json:"goal,omitempty"`
	CurCount      int32                   `protobuf:"varint,2,opt,name=cur_count,json=curCount,proto3" json:"cur_count,omitempty"` //当前局数
	MatchRem      int32                   `protobuf:"varint,3,opt,name=match_rem,json=matchRem,proto3" json:"match_rem,omitempty"`
	VideoRem      int32                   `protobuf:"varint,4,opt,name=video_rem,json=videoRem,proto3" json:"video_rem,omitempty"`
	Wheel         []*EngageWheelRewardCfg `protobuf:"bytes,5,rep,name=wheel,proto3" json:"wheel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngagePanelAck) Reset() {
	*x = EngagePanelAck{}
	mi := &file_activity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagePanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagePanelAck) ProtoMessage() {}

func (x *EngagePanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagePanelAck.ProtoReflect.Descriptor instead.
func (*EngagePanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{25}
}

func (x *EngagePanelAck) GetGoal() int32 {
	if x != nil {
		return x.Goal
	}
	return 0
}

func (x *EngagePanelAck) GetCurCount() int32 {
	if x != nil {
		return x.CurCount
	}
	return 0
}

func (x *EngagePanelAck) GetMatchRem() int32 {
	if x != nil {
		return x.MatchRem
	}
	return 0
}

func (x *EngagePanelAck) GetVideoRem() int32 {
	if x != nil {
		return x.VideoRem
	}
	return 0
}

func (x *EngagePanelAck) GetWheel() []*EngageWheelRewardCfg {
	if x != nil {
		return x.Wheel
	}
	return nil
}

type EngageWheelRewardCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[int32]int64        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Prob          int64                  `protobuf:"varint,2,opt,name=prob,proto3" json:"prob,omitempty"` // integer weight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngageWheelRewardCfg) Reset() {
	*x = EngageWheelRewardCfg{}
	mi := &file_activity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngageWheelRewardCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngageWheelRewardCfg) ProtoMessage() {}

func (x *EngageWheelRewardCfg) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngageWheelRewardCfg.ProtoReflect.Descriptor instead.
func (*EngageWheelRewardCfg) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{26}
}

func (x *EngageWheelRewardCfg) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *EngageWheelRewardCfg) GetProb() int64 {
	if x != nil {
		return x.Prob
	}
	return 0
}

type EngageRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "wheel" or "video"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngageRewardReq) Reset() {
	*x = EngageRewardReq{}
	mi := &file_activity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngageRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngageRewardReq) ProtoMessage() {}

func (x *EngageRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngageRewardReq.ProtoReflect.Descriptor instead.
func (*EngageRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{27}
}

func (x *EngageRewardReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type EngageRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "wheel" or "video"
	MatchRem      int32                  `protobuf:"varint,2,opt,name=match_rem,json=matchRem,proto3" json:"match_rem,omitempty"`
	VideoRem      int32                  `protobuf:"varint,3,opt,name=video_rem,json=videoRem,proto3" json:"video_rem,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngageRewardAck) Reset() {
	*x = EngageRewardAck{}
	mi := &file_activity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngageRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngageRewardAck) ProtoMessage() {}

func (x *EngageRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngageRewardAck.ProtoReflect.Descriptor instead.
func (*EngageRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{28}
}

func (x *EngageRewardAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EngageRewardAck) GetMatchRem() int32 {
	if x != nil {
		return x.MatchRem
	}
	return 0
}

func (x *EngageRewardAck) GetVideoRem() int32 {
	if x != nil {
		return x.VideoRem
	}
	return 0
}

func (x *EngageRewardAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 破产礼包活动 (bankrupt) =====
type BankruptPanelAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HasActivePackage bool                   `protobuf:"varint,1,opt,name=has_active_package,json=hasActivePackage,proto3" json:"has_active_package,omitempty"` // 是否有有效的特惠礼包
	RemainingSeconds int32                  `protobuf:"varint,2,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`   // 剩余有效秒数
	Packages         []*BankruptPackageInfo `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`                                            // 礼包列表
	PurchasedPackage int32                  `protobuf:"varint,4,opt,name=purchased_package,json=purchasedPackage,proto3" json:"purchased_package,omitempty"`   // 已购买的礼包档位（0表示未购买）
	TriggerCount     int32                  `protobuf:"varint,5,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`               // 触发次数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BankruptPanelAck) Reset() {
	*x = BankruptPanelAck{}
	mi := &file_activity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankruptPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankruptPanelAck) ProtoMessage() {}

func (x *BankruptPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankruptPanelAck.ProtoReflect.Descriptor instead.
func (*BankruptPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{29}
}

func (x *BankruptPanelAck) GetHasActivePackage() bool {
	if x != nil {
		return x.HasActivePackage
	}
	return false
}

func (x *BankruptPanelAck) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

func (x *BankruptPanelAck) GetPackages() []*BankruptPackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *BankruptPanelAck) GetPurchasedPackage() int32 {
	if x != nil {
		return x.PurchasedPackage
	}
	return 0
}

func (x *BankruptPanelAck) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

type BankruptPackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceOrig     int32                  `protobuf:"varint,2,opt,name=price_orig,json=priceOrig,proto3" json:"price_orig,omitempty"`                                                   // 原价（分）
	PriceDisc     int32                  `protobuf:"varint,3,opt,name=price_disc,json=priceDisc,proto3" json:"price_disc,omitempty"`                                                   // 折扣价（分）
	BonusRate     int32                  `protobuf:"varint,4,opt,name=bonus_rate,json=bonusRate,proto3" json:"bonus_rate,omitempty"`                                                   // 加赠百分比
	Items         map[int32]int64        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励道具
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankruptPackageInfo) Reset() {
	*x = BankruptPackageInfo{}
	mi := &file_activity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankruptPackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankruptPackageInfo) ProtoMessage() {}

func (x *BankruptPackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankruptPackageInfo.ProtoReflect.Descriptor instead.
func (*BankruptPackageInfo) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{30}
}

func (x *BankruptPackageInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankruptPackageInfo) GetPriceOrig() int32 {
	if x != nil {
		return x.PriceOrig
	}
	return 0
}

func (x *BankruptPackageInfo) GetPriceDisc() int32 {
	if x != nil {
		return x.PriceDisc
	}
	return 0
}

func (x *BankruptPackageInfo) GetBonusRate() int32 {
	if x != nil {
		return x.BonusRate
	}
	return 0
}

func (x *BankruptPackageInfo) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 折扣礼包活动 (discount) =====
type DiscountPanelAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Packages         []*DiscountPackageInfo `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`                                          // 礼包列表
	DailyPurchased   bool                   `protobuf:"varint,2,opt,name=daily_purchased,json=dailyPurchased,proto3" json:"daily_purchased,omitempty"`       // 今日是否已购买每日礼包
	WeeklyPurchased  bool                   `protobuf:"varint,3,opt,name=weekly_purchased,json=weeklyPurchased,proto3" json:"weekly_purchased,omitempty"`    // 本周是否已购买每周礼包
	MonthlyPurchased bool                   `protobuf:"varint,4,opt,name=monthly_purchased,json=monthlyPurchased,proto3" json:"monthly_purchased,omitempty"` // 本月是否已购买每月礼包
	Enabled          bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`                                           // 是否启用（需先购买破冰礼包）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscountPanelAck) Reset() {
	*x = DiscountPanelAck{}
	mi := &file_activity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountPanelAck) ProtoMessage() {}

func (x *DiscountPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountPanelAck.ProtoReflect.Descriptor instead.
func (*DiscountPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{31}
}

func (x *DiscountPanelAck) GetPackages() []*DiscountPackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *DiscountPanelAck) GetDailyPurchased() bool {
	if x != nil {
		return x.DailyPurchased
	}
	return false
}

func (x *DiscountPanelAck) GetWeeklyPurchased() bool {
	if x != nil {
		return x.WeeklyPurchased
	}
	return false
}

func (x *DiscountPanelAck) GetMonthlyPurchased() bool {
	if x != nil {
		return x.MonthlyPurchased
	}
	return false
}

func (x *DiscountPanelAck) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DiscountPackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceOrig     int32                  `protobuf:"varint,2,opt,name=price_orig,json=priceOrig,proto3" json:"price_orig,omitempty"`                                                   // 原价（分）
	PriceDisc     int32                  `protobuf:"varint,3,opt,name=price_disc,json=priceDisc,proto3" json:"price_disc,omitempty"`                                                   // 折扣价（分）
	BonusRate     int32                  `protobuf:"varint,4,opt,name=bonus_rate,json=bonusRate,proto3" json:"bonus_rate,omitempty"`                                                   // 加赠百分比
	Items         map[int32]int64        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励道具
	Purchased     bool                   `protobuf:"varint,6,opt,name=purchased,proto3" json:"purchased,omitempty"`                                                                    // 是否已购买
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscountPackageInfo) Reset() {
	*x = DiscountPackageInfo{}
	mi := &file_activity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountPackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountPackageInfo) ProtoMessage() {}

func (x *DiscountPackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountPackageInfo.ProtoReflect.Descriptor instead.
func (*DiscountPackageInfo) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{32}
}

func (x *DiscountPackageInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DiscountPackageInfo) GetPriceOrig() int32 {
	if x != nil {
		return x.PriceOrig
	}
	return 0
}

func (x *DiscountPackageInfo) GetPriceDisc() int32 {
	if x != nil {
		return x.PriceDisc
	}
	return 0
}

func (x *DiscountPackageInfo) GetBonusRate() int32 {
	if x != nil {
		return x.BonusRate
	}
	return 0
}

func (x *DiscountPackageInfo) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DiscountPackageInfo) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

// ===== 破冰礼包活动 (icebreaker) =====
type IcebreakerPanel struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Packages      []*IcebreakerPackageInfo `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`    // 礼包列表
	Purchased     bool                     `protobuf:"varint,2,opt,name=purchased,proto3" json:"purchased,omitempty"` // 是否已购买
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebreakerPanel) Reset() {
	*x = IcebreakerPanel{}
	mi := &file_activity_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebreakerPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebreakerPanel) ProtoMessage() {}

func (x *IcebreakerPanel) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebreakerPanel.ProtoReflect.Descriptor instead.
func (*IcebreakerPanel) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{33}
}

func (x *IcebreakerPanel) GetPackages() []*IcebreakerPackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *IcebreakerPanel) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

type IcebreakerPackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceOrig     int32                  `protobuf:"varint,2,opt,name=price_orig,json=priceOrig,proto3" json:"price_orig,omitempty"`                                                   // 原价（分）
	PriceDisc     int32                  `protobuf:"varint,3,opt,name=price_disc,json=priceDisc,proto3" json:"price_disc,omitempty"`                                                   // 折扣价（分）
	BonusRate     int32                  `protobuf:"varint,4,opt,name=bonus_rate,json=bonusRate,proto3" json:"bonus_rate,omitempty"`                                                   // 加赠百分比
	Items         map[int32]int64        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励道具
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebreakerPackageInfo) Reset() {
	*x = IcebreakerPackageInfo{}
	mi := &file_activity_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebreakerPackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebreakerPackageInfo) ProtoMessage() {}

func (x *IcebreakerPackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebreakerPackageInfo.ProtoReflect.Descriptor instead.
func (*IcebreakerPackageInfo) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{34}
}

func (x *IcebreakerPackageInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IcebreakerPackageInfo) GetPriceOrig() int32 {
	if x != nil {
		return x.PriceOrig
	}
	return 0
}

func (x *IcebreakerPackageInfo) GetPriceDisc() int32 {
	if x != nil {
		return x.PriceDisc
	}
	return 0
}

func (x *IcebreakerPackageInfo) GetBonusRate() int32 {
	if x != nil {
		return x.BonusRate
	}
	return 0
}

func (x *IcebreakerPackageInfo) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 通用购买请求/响应 (bankrupt, discount, icebreaker) =====
type ActPurchaseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     int32                  `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"` // 要购买的礼包ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActPurchaseReq) Reset() {
	*x = ActPurchaseReq{}
	mi := &file_activity_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActPurchaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActPurchaseReq) ProtoMessage() {}

func (x *ActPurchaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActPurchaseReq.ProtoReflect.Descriptor instead.
func (*ActPurchaseReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{35}
}

func (x *ActPurchaseReq) GetPackageId() int32 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

type ActPurchaseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     int32                  `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 发放的奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActPurchaseAck) Reset() {
	*x = ActPurchaseAck{}
	mi := &file_activity_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActPurchaseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActPurchaseAck) ProtoMessage() {}

func (x *ActPurchaseAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActPurchaseAck.ProtoReflect.Descriptor instead.
func (*ActPurchaseAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{36}
}

func (x *ActPurchaseAck) GetPackageId() int32 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *ActPurchaseAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// ===== 用餐时间活动 (mealtime) =====
type MealtimePanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lunch         int32                  `protobuf:"varint,1,opt,name=lunch,proto3" json:"lunch,omitempty"`   // 午间是否已领取: 0未领取 1已领取
	Dinner        int32                  `protobuf:"varint,2,opt,name=dinner,proto3" json:"dinner,omitempty"` // 晚间是否已领取: 0未领取 1已领取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealtimePanelAck) Reset() {
	*x = MealtimePanelAck{}
	mi := &file_activity_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealtimePanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealtimePanelAck) ProtoMessage() {}

func (x *MealtimePanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealtimePanelAck.ProtoReflect.Descriptor instead.
func (*MealtimePanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{37}
}

func (x *MealtimePanelAck) GetLunch() int32 {
	if x != nil {
		return x.Lunch
	}
	return 0
}

func (x *MealtimePanelAck) GetDinner() int32 {
	if x != nil {
		return x.Dinner
	}
	return 0
}

type MealtimeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "lunch" 午间打卡, "dinner" 晚间打卡
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealtimeReq) Reset() {
	*x = MealtimeReq{}
	mi := &file_activity_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealtimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealtimeReq) ProtoMessage() {}

func (x *MealtimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealtimeReq.ProtoReflect.Descriptor instead.
func (*MealtimeReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{38}
}

func (x *MealtimeReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type MealtimeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 奖励物品
	Lunch         int32                  `protobuf:"varint,3,opt,name=lunch,proto3" json:"lunch,omitempty"`                                                                            // 午间是否已领取
	Dinner        int32                  `protobuf:"varint,4,opt,name=dinner,proto3" json:"dinner,omitempty"`                                                                          // 晚间是否已领取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealtimeAck) Reset() {
	*x = MealtimeAck{}
	mi := &file_activity_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealtimeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealtimeAck) ProtoMessage() {}

func (x *MealtimeAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealtimeAck.ProtoReflect.Descriptor instead.
func (*MealtimeAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{39}
}

func (x *MealtimeAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MealtimeAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MealtimeAck) GetLunch() int32 {
	if x != nil {
		return x.Lunch
	}
	return 0
}

func (x *MealtimeAck) GetDinner() int32 {
	if x != nil {
		return x.Dinner
	}
	return 0
}

// ===== 七日签到活动 (sevensign) =====
type SignDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"` // 1-7, 周一到周日
	RewardItems   map[int32]int64        `protobuf:"bytes,2,rep,name=reward_items,json=rewardItems,proto3" json:"reward_items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Base          bool                   `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`         // true=已领基础 false=未领
	Video         bool                   `protobuf:"varint,4,opt,name=video,proto3" json:"video,omitempty"`       // true=已领视频额外 false=未领
	Recharge      int32                  `protobuf:"varint,5,opt,name=recharge,proto3" json:"recharge,omitempty"` // 0=不可领 1=可领 2=已领
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDay) Reset() {
	*x = SignDay{}
	mi := &file_activity_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDay) ProtoMessage() {}

func (x *SignDay) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDay.ProtoReflect.Descriptor instead.
func (*SignDay) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{40}
}

func (x *SignDay) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *SignDay) GetRewardItems() map[int32]int64 {
	if x != nil {
		return x.RewardItems
	}
	return nil
}

func (x *SignDay) GetBase() bool {
	if x != nil {
		return x.Base
	}
	return false
}

func (x *SignDay) GetVideo() bool {
	if x != nil {
		return x.Video
	}
	return false
}

func (x *SignDay) GetRecharge() int32 {
	if x != nil {
		return x.Recharge
	}
	return 0
}

type SevenSignPanelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodayWeekday  int32                  `protobuf:"varint,1,opt,name=today_weekday,json=todayWeekday,proto3" json:"today_weekday,omitempty"` // 1-7, 周一到周日
	Days          []*SignDay             `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	SignedDays    int32                  `protobuf:"varint,3,opt,name=signed_days,json=signedDays,proto3" json:"signed_days,omitempty"`          // 已完成签到天数（以 base_claimed 计数）
	MilestoneMask uint32                 `protobuf:"varint,4,opt,name=milestone_mask,json=milestoneMask,proto3" json:"milestone_mask,omitempty"` // 累计奖励已领取档位：bit0=2天 bit1=3天 bit2=5天 bit3=6天
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SevenSignPanelAck) Reset() {
	*x = SevenSignPanelAck{}
	mi := &file_activity_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SevenSignPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SevenSignPanelAck) ProtoMessage() {}

func (x *SevenSignPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SevenSignPanelAck.ProtoReflect.Descriptor instead.
func (*SevenSignPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{41}
}

func (x *SevenSignPanelAck) GetTodayWeekday() int32 {
	if x != nil {
		return x.TodayWeekday
	}
	return 0
}

func (x *SevenSignPanelAck) GetDays() []*SignDay {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *SevenSignPanelAck) GetSignedDays() int32 {
	if x != nil {
		return x.SignedDays
	}
	return 0
}

func (x *SevenSignPanelAck) GetMilestoneMask() uint32 {
	if x != nil {
		return x.MilestoneMask
	}
	return 0
}

type SevenSignRewardReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action:
	// "base"      今日签到（基础奖励）
	// "video"     看广告：用于“补签基础奖励(天<今日)”或“看广告额外奖励(天已基础领取)”
	// "recharge"  领取因当日充值产生的额外奖励
	// "milestone" 累计签到大奖：由前端手动触发领取
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// day: 1-7（用于 base/video/recharge)
	Day           int32 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SevenSignRewardReq) Reset() {
	*x = SevenSignRewardReq{}
	mi := &file_activity_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SevenSignRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SevenSignRewardReq) ProtoMessage() {}

func (x *SevenSignRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SevenSignRewardReq.ProtoReflect.Descriptor instead.
func (*SevenSignRewardReq) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{42}
}

func (x *SevenSignRewardReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SevenSignRewardReq) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type SevenSignRewardAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 领取到的奖励
	Panel         *SevenSignPanelAck     `protobuf:"bytes,3,opt,name=panel,proto3" json:"panel,omitempty"`                                                                             // 面板数据（领奖后用于刷新 UI）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SevenSignRewardAck) Reset() {
	*x = SevenSignRewardAck{}
	mi := &file_activity_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SevenSignRewardAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SevenSignRewardAck) ProtoMessage() {}

func (x *SevenSignRewardAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SevenSignRewardAck.ProtoReflect.Descriptor instead.
func (*SevenSignRewardAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{43}
}

func (x *SevenSignRewardAck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SevenSignRewardAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SevenSignRewardAck) GetPanel() *SevenSignPanelAck {
	if x != nil {
		return x.Panel
	}
	return nil
}

// ===== 存鑫鑵活动 (piggybank) =====
type PiggyBankPanelAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentPackage int32                  `protobuf:"varint,1,opt,name=current_package,json=currentPackage,proto3" json:"current_package,omitempty"` // 当前档位: 1=6元, 2=18元
	Progress       int64                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`                                   // 当前档位进度
	Target         int64                  `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`                                       // 当前档位目标
	Price          int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                                         // 当前档位价格（分）
	CanPurchase    bool                   `protobuf:"varint,5,opt,name=can_purchase,json=canPurchase,proto3" json:"can_purchase,omitempty"`          // 当前档位是否可购买
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PiggyBankPanelAck) Reset() {
	*x = PiggyBankPanelAck{}
	mi := &file_activity_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiggyBankPanelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiggyBankPanelAck) ProtoMessage() {}

func (x *PiggyBankPanelAck) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiggyBankPanelAck.ProtoReflect.Descriptor instead.
func (*PiggyBankPanelAck) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{44}
}

func (x *PiggyBankPanelAck) GetCurrentPackage() int32 {
	if x != nil {
		return x.CurrentPackage
	}
	return 0
}

func (x *PiggyBankPanelAck) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PiggyBankPanelAck) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *PiggyBankPanelAck) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PiggyBankPanelAck) GetCanPurchase() bool {
	if x != nil {
		return x.CanPurchase
	}
	return false
}

var File_activity_proto protoreflect.FileDescriptor

const file_activity_proto_rawDesc = "" +
	"\n" +
	"\x0eactivity.proto\x12\x06cproto\x1a\x19google/protobuf/any.proto\"5\n" +
	"\vActivityReq\x12&\n" +
	"\x03req\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03req\"5\n" +
	"\vActivityAck\x12&\n" +
	"\x03ack\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03ack\"\r\n" +
	"\vActsListReq\"L\n" +
	"\vActsListAck\x12\x17\n" +
	"\ared_dot\x18\x01 \x01(\bR\x06redDot\x12$\n" +
	"\x04acts\x18\x02 \x03(\v2\x10.cproto.ActBriefR\x04acts\".\n" +
	"\vActPanelReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\"V\n" +
	"\vActPanelAck\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12&\n" +
	"\x03ack\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03ack\"W\n" +
	"\fActRewardReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12&\n" +
	"\x03req\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03req\"W\n" +
	"\fActRewardAck\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12&\n" +
	"\x03ack\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03ack\"\x81\x01\n" +
	"\bActBrief\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.cproto.ActStatusR\x06status\x12\x15\n" +
	"\x06end_ts\x18\x04 \x01(\x03R\x05endTs\"\xbb\x01\n" +
	"\x0ePurchasePkgAck\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12\x15\n" +
	"\x06pkg_id\x18\x02 \x01(\x05R\x05pkgId\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.cproto.PurchasePkgAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eInvitePanelAck\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"invite_cnt\x18\x02 \x01(\x05R\tinviteCnt\x123\n" +
	"\arewards\x18\x03 \x03(\v2\x19.cproto.InviteRewardStateR\arewards\x12(\n" +
	"\x05users\x18\x04 \x03(\v2\x12.cproto.InviteUserR\x05users\"\xfb\x01\n" +
	"\x11InviteRewardState\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x12\n" +
	"\x04cond\x18\x02 \x01(\x05R\x04cond\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12\x10\n" +
	"\x03got\x18\x04 \x01(\bR\x03got\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12:\n" +
	"\x05items\x18\x06 \x03(\v2$.cproto.InviteRewardState.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"@\n" +
	"\n" +
	"InviteUser\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"#\n" +
	"\x0fInviteRewardReq\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\"\x97\x01\n" +
	"\x0fInviteRewardAck\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".cproto.InviteRewardAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"+\n" +
	"\x11RedpacketPanelAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"M\n" +
	"\x14RedpacketRcvPanelAck\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\tR\tsenderUid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"E\n" +
	"\fRedpacketReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x02 \x01(\tR\tsenderUid\"\xb6\x01\n" +
	"\fRedpacketAck\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\tR\tsenderUid\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x125\n" +
	"\x05items\x18\x03 \x03(\v2\x1f.cproto.RedpacketAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"D\n" +
	"\rLuckyPanelAck\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"left_count\x18\x02 \x01(\x05R\tleftCount\"\"\n" +
	"\bLuckyReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\xc4\x01\n" +
	"\bLuckyAck\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.cproto.LuckyAck.ItemsEntryR\x05items\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"left_count\x18\x04 \x01(\x05R\tleftCount\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc6\x02\n" +
	"\x10RegisterPanelAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12L\n" +
	"\fnormal_items\x18\x02 \x03(\v2).cproto.RegisterPanelAck.NormalItemsEntryR\vnormalItems\x12L\n" +
	"\fdouble_items\x18\x03 \x03(\v2).cproto.RegisterPanelAck.DoubleItemsEntryR\vdoubleItems\x1a>\n" +
	"\x10NormalItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10DoubleItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"+\n" +
	"\x11RegisterRewardReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\xa1\x01\n" +
	"\x11RegisterRewardAck\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.cproto.RegisterRewardAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eEngagePanelAck\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\x05R\x04goal\x12\x1b\n" +
	"\tcur_count\x18\x02 \x01(\x05R\bcurCount\x12\x1b\n" +
	"\tmatch_rem\x18\x03 \x01(\x05R\bmatchRem\x12\x1b\n" +
	"\tvideo_rem\x18\x04 \x01(\x05R\bvideoRem\x122\n" +
	"\x05wheel\x18\x05 \x03(\v2\x1c.cproto.EngageWheelRewardCfgR\x05wheel\"\xa3\x01\n" +
	"\x14EngageWheelRewardCfg\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.cproto.EngageWheelRewardCfg.ItemsEntryR\x05items\x12\x12\n" +
	"\x04prob\x18\x02 \x01(\x03R\x04prob\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\")\n" +
	"\x0fEngageRewardReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\xd7\x01\n" +
	"\x0fEngageRewardAck\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\tmatch_rem\x18\x02 \x01(\x05R\bmatchRem\x12\x1b\n" +
	"\tvideo_rem\x18\x03 \x01(\x05R\bvideoRem\x128\n" +
	"\x05items\x18\x04 \x03(\v2\".cproto.EngageRewardAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf8\x01\n" +
	"\x10BankruptPanelAck\x12,\n" +
	"\x12has_active_package\x18\x01 \x01(\bR\x10hasActivePackage\x12+\n" +
	"\x11remaining_seconds\x18\x02 \x01(\x05R\x10remainingSeconds\x127\n" +
	"\bpackages\x18\x03 \x03(\v2\x1b.cproto.BankruptPackageInfoR\bpackages\x12+\n" +
	"\x11purchased_package\x18\x04 \x01(\x05R\x10purchasedPackage\x12#\n" +
	"\rtrigger_count\x18\x05 \x01(\x05R\ftriggerCount\"\xfa\x01\n" +
	"\x13BankruptPackageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"price_orig\x18\x02 \x01(\x05R\tpriceOrig\x12\x1d\n" +
	"\n" +
	"price_disc\x18\x03 \x01(\x05R\tpriceDisc\x12\x1d\n" +
	"\n" +
	"bonus_rate\x18\x04 \x01(\x05R\tbonusRate\x12<\n" +
	"\x05items\x18\x05 \x03(\v2&.cproto.BankruptPackageInfo.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xe6\x01\n" +
	"\x10DiscountPanelAck\x127\n" +
	"\bpackages\x18\x01 \x03(\v2\x1b.cproto.DiscountPackageInfoR\bpackages\x12'\n" +
	"\x0fdaily_purchased\x18\x02 \x01(\bR\x0edailyPurchased\x12)\n" +
	"\x10weekly_purchased\x18\x03 \x01(\bR\x0fweeklyPurchased\x12+\n" +
	"\x11monthly_purchased\x18\x04 \x01(\bR\x10monthlyPurchased\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"\x98\x02\n" +
	"\x13DiscountPackageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"price_orig\x18\x02 \x01(\x05R\tpriceOrig\x12\x1d\n" +
	"\n" +
	"price_disc\x18\x03 \x01(\x05R\tpriceDisc\x12\x1d\n" +
	"\n" +
	"bonus_rate\x18\x04 \x01(\x05R\tbonusRate\x12<\n" +
	"\x05items\x18\x05 \x03(\v2&.cproto.DiscountPackageInfo.ItemsEntryR\x05items\x12\x1c\n" +
	"\tpurchased\x18\x06 \x01(\bR\tpurchased\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"j\n" +
	"\x0fIcebreakerPanel\x129\n" +
	"\bpackages\x18\x01 \x03(\v2\x1d.cproto.IcebreakerPackageInfoR\bpackages\x12\x1c\n" +
	"\tpurchased\x18\x02 \x01(\bR\tpurchased\"\xfe\x01\n" +
	"\x15IcebreakerPackageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"price_orig\x18\x02 \x01(\x05R\tpriceOrig\x12\x1d\n" +
	"\n" +
	"price_disc\x18\x03 \x01(\x05R\tpriceDisc\x12\x1d\n" +
	"\n" +
	"bonus_rate\x18\x04 \x01(\x05R\tbonusRate\x12>\n" +
	"\x05items\x18\x05 \x03(\v2(.cproto.IcebreakerPackageInfo.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"/\n" +
	"\x0eActPurchaseReq\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\x05R\tpackageId\"\xa2\x01\n" +
	"\x0eActPurchaseAck\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\x05R\tpackageId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.cproto.ActPurchaseAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"@\n" +
	"\x10MealtimePanelAck\x12\x14\n" +
	"\x05lunch\x18\x01 \x01(\x05R\x05lunch\x12\x16\n" +
	"\x06dinner\x18\x02 \x01(\x05R\x06dinner\"%\n" +
	"\vMealtimeReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\xc3\x01\n" +
	"\vMealtimeAck\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.cproto.MealtimeAck.ItemsEntryR\x05items\x12\x14\n" +
	"\x05lunch\x18\x03 \x01(\x05R\x05lunch\x12\x16\n" +
	"\x06dinner\x18\x04 \x01(\x05R\x06dinner\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xe6\x01\n" +
	"\aSignDay\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12C\n" +
	"\freward_items\x18\x02 \x03(\v2 .cproto.SignDay.RewardItemsEntryR\vrewardItems\x12\x12\n" +
	"\x04base\x18\x03 \x01(\bR\x04base\x12\x14\n" +
	"\x05video\x18\x04 \x01(\bR\x05video\x12\x1a\n" +
	"\brecharge\x18\x05 \x01(\x05R\brecharge\x1a>\n" +
	"\x10RewardItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa5\x01\n" +
	"\x11SevenSignPanelAck\x12#\n" +
	"\rtoday_weekday\x18\x01 \x01(\x05R\ftodayWeekday\x12#\n" +
	"\x04days\x18\x02 \x03(\v2\x0f.cproto.SignDayR\x04days\x12\x1f\n" +
	"\vsigned_days\x18\x03 \x01(\x05R\n" +
	"signedDays\x12%\n" +
	"\x0emilestone_mask\x18\x04 \x01(\rR\rmilestoneMask\">\n" +
	"\x12SevenSignRewardReq\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\"\xd4\x01\n" +
	"\x12SevenSignRewardAck\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12;\n" +
	"\x05items\x18\x02 \x03(\v2%.cproto.SevenSignRewardAck.ItemsEntryR\x05items\x12/\n" +
	"\x05panel\x18\x03 \x01(\v2\x19.cproto.SevenSignPanelAckR\x05panel\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa9\x01\n" +
	"\x11PiggyBankPanelAck\x12'\n" +
	"\x0fcurrent_package\x18\x01 \x01(\x05R\x0ecurrentPackage\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x03R\bprogress\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x03R\x06target\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12!\n" +
	"\fcan_purchase\x18\x05 \x01(\bR\vcanPurchase*N\n" +
	"\tActStatus\x12\x0e\n" +
	"\n" +
	"NotStarted\x10\x00\x12\r\n" +
	"\tClaimable\x10\x01\x12\x10\n" +
	"\fParticipable\x10\x02\x12\x10\n" +
	"\fFullyClaimed\x10\x03B\vZ\t../cprotob\x06proto3"

var (
	file_activity_proto_rawDescOnce sync.Once
	file_activity_proto_rawDescData []byte
)

func file_activity_proto_rawDescGZIP() []byte {
	file_activity_proto_rawDescOnce.Do(func() {
		file_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_proto_rawDesc), len(file_activity_proto_rawDesc)))
	})
	return file_activity_proto_rawDescData
}

var file_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 62)
var file_activity_proto_goTypes = []any{
	(ActStatus)(0),                // 0: cproto.ActStatus
	(*ActivityReq)(nil),           // 1: cproto.ActivityReq
	(*ActivityAck)(nil),           // 2: cproto.ActivityAck
	(*ActsListReq)(nil),           // 3: cproto.ActsListReq
	(*ActsListAck)(nil),           // 4: cproto.ActsListAck
	(*ActPanelReq)(nil),           // 5: cproto.ActPanelReq
	(*ActPanelAck)(nil),           // 6: cproto.ActPanelAck
	(*ActRewardReq)(nil),          // 7: cproto.ActRewardReq
	(*ActRewardAck)(nil),          // 8: cproto.ActRewardAck
	(*ActBrief)(nil),              // 9: cproto.ActBrief
	(*PurchasePkgAck)(nil),        // 10: cproto.PurchasePkgAck
	(*InvitePanelAck)(nil),        // 11: cproto.InvitePanelAck
	(*InviteRewardState)(nil),     // 12: cproto.InviteRewardState
	(*InviteUser)(nil),            // 13: cproto.InviteUser
	(*InviteRewardReq)(nil),       // 14: cproto.InviteRewardReq
	(*InviteRewardAck)(nil),       // 15: cproto.InviteRewardAck
	(*RedpacketPanelAck)(nil),     // 16: cproto.RedpacketPanelAck
	(*RedpacketRcvPanelAck)(nil),  // 17: cproto.RedpacketRcvPanelAck
	(*RedpacketReq)(nil),          // 18: cproto.RedpacketReq
	(*RedpacketAck)(nil),          // 19: cproto.RedpacketAck
	(*LuckyPanelAck)(nil),         // 20: cproto.LuckyPanelAck
	(*LuckyReq)(nil),              // 21: cproto.LuckyReq
	(*LuckyAck)(nil),              // 22: cproto.LuckyAck
	(*RegisterPanelAck)(nil),      // 23: cproto.RegisterPanelAck
	(*RegisterRewardReq)(nil),     // 24: cproto.RegisterRewardReq
	(*RegisterRewardAck)(nil),     // 25: cproto.RegisterRewardAck
	(*EngagePanelAck)(nil),        // 26: cproto.EngagePanelAck
	(*EngageWheelRewardCfg)(nil),  // 27: cproto.EngageWheelRewardCfg
	(*EngageRewardReq)(nil),       // 28: cproto.EngageRewardReq
	(*EngageRewardAck)(nil),       // 29: cproto.EngageRewardAck
	(*BankruptPanelAck)(nil),      // 30: cproto.BankruptPanelAck
	(*BankruptPackageInfo)(nil),   // 31: cproto.BankruptPackageInfo
	(*DiscountPanelAck)(nil),      // 32: cproto.DiscountPanelAck
	(*DiscountPackageInfo)(nil),   // 33: cproto.DiscountPackageInfo
	(*IcebreakerPanel)(nil),       // 34: cproto.IcebreakerPanel
	(*IcebreakerPackageInfo)(nil), // 35: cproto.IcebreakerPackageInfo
	(*ActPurchaseReq)(nil),        // 36: cproto.ActPurchaseReq
	(*ActPurchaseAck)(nil),        // 37: cproto.ActPurchaseAck
	(*MealtimePanelAck)(nil),      // 38: cproto.MealtimePanelAck
	(*MealtimeReq)(nil),           // 39: cproto.MealtimeReq
	(*MealtimeAck)(nil),           // 40: cproto.MealtimeAck
	(*SignDay)(nil),               // 41: cproto.SignDay
	(*SevenSignPanelAck)(nil),     // 42: cproto.SevenSignPanelAck
	(*SevenSignRewardReq)(nil),    // 43: cproto.SevenSignRewardReq
	(*SevenSignRewardAck)(nil),    // 44: cproto.SevenSignRewardAck
	(*PiggyBankPanelAck)(nil),     // 45: cproto.PiggyBankPanelAck
	nil,                           // 46: cproto.PurchasePkgAck.ItemsEntry
	nil,                           // 47: cproto.InviteRewardState.ItemsEntry
	nil,                           // 48: cproto.InviteRewardAck.ItemsEntry
	nil,                           // 49: cproto.RedpacketAck.ItemsEntry
	nil,                           // 50: cproto.LuckyAck.ItemsEntry
	nil,                           // 51: cproto.RegisterPanelAck.NormalItemsEntry
	nil,                           // 52: cproto.RegisterPanelAck.DoubleItemsEntry
	nil,                           // 53: cproto.RegisterRewardAck.ItemsEntry
	nil,                           // 54: cproto.EngageWheelRewardCfg.ItemsEntry
	nil,                           // 55: cproto.EngageRewardAck.ItemsEntry
	nil,                           // 56: cproto.BankruptPackageInfo.ItemsEntry
	nil,                           // 57: cproto.DiscountPackageInfo.ItemsEntry
	nil,                           // 58: cproto.IcebreakerPackageInfo.ItemsEntry
	nil,                           // 59: cproto.ActPurchaseAck.ItemsEntry
	nil,                           // 60: cproto.MealtimeAck.ItemsEntry
	nil,                           // 61: cproto.SignDay.RewardItemsEntry
	nil,                           // 62: cproto.SevenSignRewardAck.ItemsEntry
	(*anypb.Any)(nil),             // 63: google.protobuf.Any
}
var file_activity_proto_depIdxs = []int32{
	63, // 0: cproto.ActivityReq.req:type_name -> google.protobuf.Any
	63, // 1: cproto.ActivityAck.ack:type_name -> google.protobuf.Any
	9,  // 2: cproto.ActsListAck.acts:type_name -> cproto.ActBrief
	63, // 3: cproto.ActPanelAck.ack:type_name -> google.protobuf.Any
	63, // 4: cproto.ActRewardReq.req:type_name -> google.protobuf.Any
	63, // 5: cproto.ActRewardAck.ack:type_name -> google.protobuf.Any
	0,  // 6: cproto.ActBrief.status:type_name -> cproto.ActStatus
	46, // 7: cproto.PurchasePkgAck.items:type_name -> cproto.PurchasePkgAck.ItemsEntry
	12, // 8: cproto.InvitePanelAck.rewards:type_name -> cproto.InviteRewardState
	13, // 9: cproto.InvitePanelAck.users:type_name -> cproto.InviteUser
	47, // 10: cproto.InviteRewardState.items:type_name -> cproto.InviteRewardState.ItemsEntry
	48, // 11: cproto.InviteRewardAck.items:type_name -> cproto.InviteRewardAck.ItemsEntry
	49, // 12: cproto.RedpacketAck.items:type_name -> cproto.RedpacketAck.ItemsEntry
	50, // 13: cproto.LuckyAck.items:type_name -> cproto.LuckyAck.ItemsEntry
	51, // 14: cproto.RegisterPanelAck.normal_items:type_name -> cproto.RegisterPanelAck.NormalItemsEntry
	52, // 15: cproto.RegisterPanelAck.double_items:type_name -> cproto.RegisterPanelAck.DoubleItemsEntry
	53, // 16: cproto.RegisterRewardAck.items:type_name -> cproto.RegisterRewardAck.ItemsEntry
	27, // 17: cproto.EngagePanelAck.wheel:type_name -> cproto.EngageWheelRewardCfg
	54, // 18: cproto.EngageWheelRewardCfg.items:type_name -> cproto.EngageWheelRewardCfg.ItemsEntry
	55, // 19: cproto.EngageRewardAck.items:type_name -> cproto.EngageRewardAck.ItemsEntry
	31, // 20: cproto.BankruptPanelAck.packages:type_name -> cproto.BankruptPackageInfo
	56, // 21: cproto.BankruptPackageInfo.items:type_name -> cproto.BankruptPackageInfo.ItemsEntry
	33, // 22: cproto.DiscountPanelAck.packages:type_name -> cproto.DiscountPackageInfo
	57, // 23: cproto.DiscountPackageInfo.items:type_name -> cproto.DiscountPackageInfo.ItemsEntry
	35, // 24: cproto.IcebreakerPanel.packages:type_name -> cproto.IcebreakerPackageInfo
	58, // 25: cproto.IcebreakerPackageInfo.items:type_name -> cproto.IcebreakerPackageInfo.ItemsEntry
	59, // 26: cproto.ActPurchaseAck.items:type_name -> cproto.ActPurchaseAck.ItemsEntry
	60, // 27: cproto.MealtimeAck.items:type_name -> cproto.MealtimeAck.ItemsEntry
	61, // 28: cproto.SignDay.reward_items:type_name -> cproto.SignDay.RewardItemsEntry
	41, // 29: cproto.SevenSignPanelAck.days:type_name -> cproto.SignDay
	62, // 30: cproto.SevenSignRewardAck.items:type_name -> cproto.SevenSignRewardAck.ItemsEntry
	42, // 31: cproto.SevenSignRewardAck.panel:type_name -> cproto.SevenSignPanelAck
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_activity_proto_init() }
func file_activity_proto_init() {
	if File_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_proto_rawDesc), len(file_activity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   62,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_proto_goTypes,
		DependencyIndexes: file_activity_proto_depIdxs,
		EnumInfos:         file_activity_proto_enumTypes,
		MessageInfos:      file_activity_proto_msgTypes,
	}.Build()
	File_activity_proto = out.File
	file_activity_proto_goTypes = nil
	file_activity_proto_depIdxs = nil
}
