// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.3
// source: cerror.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAck) Reset() {
	*x = ErrorAck{}
	mi := &file_cerror_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAck) ProtoMessage() {}

func (x *ErrorAck) ProtoReflect() protoreflect.Message {
	mi := &file_cerror_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAck.ProtoReflect.Descriptor instead.
func (*ErrorAck) Descriptor() ([]byte, []int) {
	return file_cerror_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_cerror_proto protoreflect.FileDescriptor

const file_cerror_proto_rawDesc = "" +
	"\n" +
	"\fcerror.proto\x12\x06cproto\"P\n" +
	"\bErrorAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detailB\vZ\t../cprotob\x06proto3"

var (
	file_cerror_proto_rawDescOnce sync.Once
	file_cerror_proto_rawDescData []byte
)

func file_cerror_proto_rawDescGZIP() []byte {
	file_cerror_proto_rawDescOnce.Do(func() {
		file_cerror_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerror_proto_rawDesc), len(file_cerror_proto_rawDesc)))
	})
	return file_cerror_proto_rawDescData
}

var file_cerror_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerror_proto_goTypes = []any{
	(*ErrorAck)(nil), // 0: cproto.ErrorAck
}
var file_cerror_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cerror_proto_init() }
func file_cerror_proto_init() {
	if File_cerror_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerror_proto_rawDesc), len(file_cerror_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerror_proto_goTypes,
		DependencyIndexes: file_cerror_proto_depIdxs,
		MessageInfos:      file_cerror_proto_msgTypes,
	}.Build()
	File_cerror_proto = out.File
	file_cerror_proto_goTypes = nil
	file_cerror_proto_depIdxs = nil
}
