// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.3
// source: account_remote.proto

package sproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           bool                   `protobuf:"varint,1,opt,name=bot,proto3" json:"bot,omitempty"` //是否为机器人
	Req           *anypb.Any             `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`  // 请求内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountReq) Reset() {
	*x = AccountReq{}
	mi := &file_account_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReq) ProtoMessage() {}

func (x *AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReq.ProtoReflect.Descriptor instead.
func (*AccountReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{0}
}

func (x *AccountReq) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *AccountReq) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

type AccountAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           bool                   `protobuf:"varint,1,opt,name=bot,proto3" json:"bot,omitempty"` //是否为机器人
	Ack           *anypb.Any             `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`  // 响应内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAck) Reset() {
	*x = AccountAck{}
	mi := &file_account_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAck) ProtoMessage() {}

func (x *AccountAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAck.ProtoReflect.Descriptor instead.
func (*AccountAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{1}
}

func (x *AccountAck) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *AccountAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

type GetBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotReq) Reset() {
	*x = GetBotReq{}
	mi := &file_account_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotReq) ProtoMessage() {}

func (x *GetBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotReq.ProtoReflect.Descriptor instead.
func (*GetBotReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{2}
}

type GetBotAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`          //机器人id
	Expired       int64                  `protobuf:"varint,2,opt,name=expired,proto3" json:"expired,omitempty"` //过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotAck) Reset() {
	*x = GetBotAck{}
	mi := &file_account_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotAck) ProtoMessage() {}

func (x *GetBotAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotAck.ProtoReflect.Descriptor instead.
func (*GetBotAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{3}
}

func (x *GetBotAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetBotAck) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

type PlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` //用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoReq) Reset() {
	*x = PlayerInfoReq{}
	mi := &file_account_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoReq) ProtoMessage() {}

func (x *PlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PlayerInfoAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 // 玩家ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                                       // 玩家昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                                           // 玩家头像
	Items         map[int32]int64        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoAck) Reset() {
	*x = PlayerInfoAck{}
	mi := &file_account_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoAck) ProtoMessage() {}

func (x *PlayerInfoAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoAck.ProtoReflect.Descriptor instead.
func (*PlayerInfoAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInfoAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PlayerInfoAck) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfoAck) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerInfoAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChangeItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 //用户id
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeItemsReq) Reset() {
	*x = ChangeItemsReq{}
	mi := &file_account_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeItemsReq) ProtoMessage() {}

func (x *ChangeItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeItemsReq.ProtoReflect.Descriptor instead.
func (*ChangeItemsReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeItemsReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeItemsReq) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChangeItemsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 //用于id
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeItemsAck) Reset() {
	*x = ChangeItemsAck{}
	mi := &file_account_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeItemsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeItemsAck) ProtoMessage() {}

func (x *ChangeItemsAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeItemsAck.ProtoReflect.Descriptor instead.
func (*ChangeItemsAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeItemsAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeItemsAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_account_remote_proto protoreflect.FileDescriptor

const file_account_remote_proto_rawDesc = "" +
	"\n" +
	"\x14account_remote.proto\x12\x06sproto\x1a\x19google/protobuf/any.proto\"F\n" +
	"\n" +
	"AccountReq\x12\x10\n" +
	"\x03bot\x18\x01 \x01(\bR\x03bot\x12&\n" +
	"\x03req\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03req\"F\n" +
	"\n" +
	"AccountAck\x12\x10\n" +
	"\x03bot\x18\x01 \x01(\bR\x03bot\x12&\n" +
	"\x03ack\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03ack\"\v\n" +
	"\tGetBotReq\"7\n" +
	"\tGetBotAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x18\n" +
	"\aexpired\x18\x02 \x01(\x03R\aexpired\"!\n" +
	"\rPlayerInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\xc7\x01\n" +
	"\rPlayerInfoAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x126\n" +
	"\x05items\x18\x04 \x03(\v2 .sproto.PlayerInfoAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x95\x01\n" +
	"\x0eChangeItemsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.sproto.ChangeItemsReq.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x95\x01\n" +
	"\x0eChangeItemsAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.sproto.ChangeItemsAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\vZ\t../sprotob\x06proto3"

var (
	file_account_remote_proto_rawDescOnce sync.Once
	file_account_remote_proto_rawDescData []byte
)

func file_account_remote_proto_rawDescGZIP() []byte {
	file_account_remote_proto_rawDescOnce.Do(func() {
		file_account_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_remote_proto_rawDesc), len(file_account_remote_proto_rawDesc)))
	})
	return file_account_remote_proto_rawDescData
}

var file_account_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_account_remote_proto_goTypes = []any{
	(*AccountReq)(nil),     // 0: sproto.AccountReq
	(*AccountAck)(nil),     // 1: sproto.AccountAck
	(*GetBotReq)(nil),      // 2: sproto.GetBotReq
	(*GetBotAck)(nil),      // 3: sproto.GetBotAck
	(*PlayerInfoReq)(nil),  // 4: sproto.PlayerInfoReq
	(*PlayerInfoAck)(nil),  // 5: sproto.PlayerInfoAck
	(*ChangeItemsReq)(nil), // 6: sproto.ChangeItemsReq
	(*ChangeItemsAck)(nil), // 7: sproto.ChangeItemsAck
	nil,                    // 8: sproto.PlayerInfoAck.ItemsEntry
	nil,                    // 9: sproto.ChangeItemsReq.ItemsEntry
	nil,                    // 10: sproto.ChangeItemsAck.ItemsEntry
	(*anypb.Any)(nil),      // 11: google.protobuf.Any
}
var file_account_remote_proto_depIdxs = []int32{
	11, // 0: sproto.AccountReq.req:type_name -> google.protobuf.Any
	11, // 1: sproto.AccountAck.ack:type_name -> google.protobuf.Any
	8,  // 2: sproto.PlayerInfoAck.items:type_name -> sproto.PlayerInfoAck.ItemsEntry
	9,  // 3: sproto.ChangeItemsReq.items:type_name -> sproto.ChangeItemsReq.ItemsEntry
	10, // 4: sproto.ChangeItemsAck.items:type_name -> sproto.ChangeItemsAck.ItemsEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_account_remote_proto_init() }
func file_account_remote_proto_init() {
	if File_account_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_remote_proto_rawDesc), len(file_account_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_remote_proto_goTypes,
		DependencyIndexes: file_account_remote_proto_depIdxs,
		MessageInfos:      file_account_remote_proto_msgTypes,
	}.Build()
	File_account_remote_proto = out.File
	file_account_remote_proto_goTypes = nil
	file_account_remote_proto_depIdxs = nil
}
