// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: account_remote.proto

package sproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           bool                   `protobuf:"varint,1,opt,name=bot,proto3" json:"bot,omitempty"` //是否为机器人
	Req           *anypb.Any             `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`  // 请求内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountReq) Reset() {
	*x = AccountReq{}
	mi := &file_account_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReq) ProtoMessage() {}

func (x *AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReq.ProtoReflect.Descriptor instead.
func (*AccountReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{0}
}

func (x *AccountReq) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *AccountReq) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

type AccountAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           bool                   `protobuf:"varint,1,opt,name=bot,proto3" json:"bot,omitempty"` //是否为机器人
	Ack           *anypb.Any             `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`  // 响应内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAck) Reset() {
	*x = AccountAck{}
	mi := &file_account_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAck) ProtoMessage() {}

func (x *AccountAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAck.ProtoReflect.Descriptor instead.
func (*AccountAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{1}
}

func (x *AccountAck) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *AccountAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

type GetBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotReq) Reset() {
	*x = GetBotReq{}
	mi := &file_account_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotReq) ProtoMessage() {}

func (x *GetBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotReq.ProtoReflect.Descriptor instead.
func (*GetBotReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{2}
}

type GetBotAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`          //机器人id
	Expired       int64                  `protobuf:"varint,2,opt,name=expired,proto3" json:"expired,omitempty"` //过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotAck) Reset() {
	*x = GetBotAck{}
	mi := &file_account_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotAck) ProtoMessage() {}

func (x *GetBotAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotAck.ProtoReflect.Descriptor instead.
func (*GetBotAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{3}
}

func (x *GetBotAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetBotAck) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

type PlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` //用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoReq) Reset() {
	*x = PlayerInfoReq{}
	mi := &file_account_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoReq) ProtoMessage() {}

func (x *PlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PlayerInfoAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 // 玩家ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                                                                       // 玩家昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                                           // 玩家头像
	Items         map[int32]int64        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoAck) Reset() {
	*x = PlayerInfoAck{}
	mi := &file_account_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoAck) ProtoMessage() {}

func (x *PlayerInfoAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoAck.ProtoReflect.Descriptor instead.
func (*PlayerInfoAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInfoAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PlayerInfoAck) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfoAck) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerInfoAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChangeItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 //用户id
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeItemsReq) Reset() {
	*x = ChangeItemsReq{}
	mi := &file_account_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeItemsReq) ProtoMessage() {}

func (x *ChangeItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeItemsReq.ProtoReflect.Descriptor instead.
func (*ChangeItemsReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeItemsReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeItemsReq) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChangeItemsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                 //用于id
	Items         map[int32]int64        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //玩家物品
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeItemsAck) Reset() {
	*x = ChangeItemsAck{}
	mi := &file_account_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeItemsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeItemsAck) ProtoMessage() {}

func (x *ChangeItemsAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeItemsAck.ProtoReflect.Descriptor instead.
func (*ChangeItemsAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeItemsAck) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeItemsAck) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

// 新手保护统计
type GetNewbieStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewbieStatsReq) Reset() {
	*x = GetNewbieStatsReq{}
	mi := &file_account_remote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewbieStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewbieStatsReq) ProtoMessage() {}

func (x *GetNewbieStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewbieStatsReq.ProtoReflect.Descriptor instead.
func (*GetNewbieStatsReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{8}
}

func (x *GetNewbieStatsReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetNewbieStatsAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MatchCount     int32                  `protobuf:"varint,1,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`             // lifetime总对局数
	Pressure       int32                  `protobuf:"varint,2,opt,name=pressure,proto3" json:"pressure,omitempty"`                                   // 压力值(连输数)
	ProtectedCount int32                  `protobuf:"varint,3,opt,name=protected_count,json=protectedCount,proto3" json:"protected_count,omitempty"` // 已消耗的新手保护局数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNewbieStatsAck) Reset() {
	*x = GetNewbieStatsAck{}
	mi := &file_account_remote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewbieStatsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewbieStatsAck) ProtoMessage() {}

func (x *GetNewbieStatsAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewbieStatsAck.ProtoReflect.Descriptor instead.
func (*GetNewbieStatsAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{9}
}

func (x *GetNewbieStatsAck) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

func (x *GetNewbieStatsAck) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *GetNewbieStatsAck) GetProtectedCount() int32 {
	if x != nil {
		return x.ProtectedCount
	}
	return 0
}

type UpdateNewbieStatsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Win             bool                   `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`                                                  // 本局是否赢
	InProtectedRoom bool                   `protobuf:"varint,3,opt,name=in_protected_room,json=inProtectedRoom,proto3" json:"in_protected_room,omitempty"` // 是否在新手/初级场保护局内
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNewbieStatsReq) Reset() {
	*x = UpdateNewbieStatsReq{}
	mi := &file_account_remote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNewbieStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNewbieStatsReq) ProtoMessage() {}

func (x *UpdateNewbieStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNewbieStatsReq.ProtoReflect.Descriptor instead.
func (*UpdateNewbieStatsReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNewbieStatsReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateNewbieStatsReq) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *UpdateNewbieStatsReq) GetInProtectedRoom() bool {
	if x != nil {
		return x.InProtectedRoom
	}
	return false
}

type UpdateNewbieStatsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNewbieStatsAck) Reset() {
	*x = UpdateNewbieStatsAck{}
	mi := &file_account_remote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNewbieStatsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNewbieStatsAck) ProtoMessage() {}

func (x *UpdateNewbieStatsAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNewbieStatsAck.ProtoReflect.Descriptor instead.
func (*UpdateNewbieStatsAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{11}
}

// 运营发货/改状态 st: 1已发货(需expr) 2已完成 3已取消
type PhysOrdShipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	St            int32                  `protobuf:"varint,2,opt,name=st,proto3" json:"st,omitempty"`
	ExprCorp      string                 `protobuf:"bytes,3,opt,name=expr_corp,json=exprCorp,proto3" json:"expr_corp,omitempty"`
	ExprNo        string                 `protobuf:"bytes,4,opt,name=expr_no,json=exprNo,proto3" json:"expr_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysOrdShipReq) Reset() {
	*x = PhysOrdShipReq{}
	mi := &file_account_remote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysOrdShipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysOrdShipReq) ProtoMessage() {}

func (x *PhysOrdShipReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysOrdShipReq.ProtoReflect.Descriptor instead.
func (*PhysOrdShipReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{12}
}

func (x *PhysOrdShipReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PhysOrdShipReq) GetSt() int32 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *PhysOrdShipReq) GetExprCorp() string {
	if x != nil {
		return x.ExprCorp
	}
	return ""
}

func (x *PhysOrdShipReq) GetExprNo() string {
	if x != nil {
		return x.ExprNo
	}
	return ""
}

type PhysOrdShipAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysOrdShipAck) Reset() {
	*x = PhysOrdShipAck{}
	mi := &file_account_remote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysOrdShipAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysOrdShipAck) ProtoMessage() {}

func (x *PhysOrdShipAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysOrdShipAck.ProtoReflect.Descriptor instead.
func (*PhysOrdShipAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{13}
}

// 运营后台：查询实物兑换订单（可用于待发货列表）
// status:
// - 0 待发货
// - 1 已发货
// - 2 已完成
// - 3 已取消
// - -1 查询全部
type PhysOrdAdminListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysOrdAdminListReq) Reset() {
	*x = PhysOrdAdminListReq{}
	mi := &file_account_remote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysOrdAdminListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysOrdAdminListReq) ProtoMessage() {}

func (x *PhysOrdAdminListReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysOrdAdminListReq.ProtoReflect.Descriptor instead.
func (*PhysOrdAdminListReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{14}
}

func (x *PhysOrdAdminListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PhysOrdAdminListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PhysOrdAdminListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PhysOrdAdminRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTs     int64                  `protobuf:"varint,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RecvName      string                 `protobuf:"bytes,6,opt,name=recv_name,json=recvName,proto3" json:"recv_name,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Addr          string                 `protobuf:"bytes,8,opt,name=addr,proto3" json:"addr,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	ExprCorp      string                 `protobuf:"bytes,10,opt,name=expr_corp,json=exprCorp,proto3" json:"expr_corp,omitempty"`
	ExprNo        string                 `protobuf:"bytes,11,opt,name=expr_no,json=exprNo,proto3" json:"expr_no,omitempty"`
	UpTs          int64                  `protobuf:"varint,12,opt,name=up_ts,json=upTs,proto3" json:"up_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysOrdAdminRow) Reset() {
	*x = PhysOrdAdminRow{}
	mi := &file_account_remote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysOrdAdminRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysOrdAdminRow) ProtoMessage() {}

func (x *PhysOrdAdminRow) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysOrdAdminRow.ProtoReflect.Descriptor instead.
func (*PhysOrdAdminRow) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{15}
}

func (x *PhysOrdAdminRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PhysOrdAdminRow) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PhysOrdAdminRow) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PhysOrdAdminRow) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *PhysOrdAdminRow) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PhysOrdAdminRow) GetRecvName() string {
	if x != nil {
		return x.RecvName
	}
	return ""
}

func (x *PhysOrdAdminRow) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhysOrdAdminRow) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PhysOrdAdminRow) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PhysOrdAdminRow) GetExprCorp() string {
	if x != nil {
		return x.ExprCorp
	}
	return ""
}

func (x *PhysOrdAdminRow) GetExprNo() string {
	if x != nil {
		return x.ExprNo
	}
	return ""
}

func (x *PhysOrdAdminRow) GetUpTs() int64 {
	if x != nil {
		return x.UpTs
	}
	return 0
}

type PhysOrdAdminListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*PhysOrdAdminRow     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysOrdAdminListAck) Reset() {
	*x = PhysOrdAdminListAck{}
	mi := &file_account_remote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysOrdAdminListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysOrdAdminListAck) ProtoMessage() {}

func (x *PhysOrdAdminListAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysOrdAdminListAck.ProtoReflect.Descriptor instead.
func (*PhysOrdAdminListAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{16}
}

func (x *PhysOrdAdminListAck) GetRows() []*PhysOrdAdminRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *PhysOrdAdminListAck) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 运营后台：查询虚拟兑换订单（话费/京东卡）
// status:
// - 0 待处理
// - 2 已完成
// - 3 已取消
// - -1 查询全部
type VirtOrdAdminListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtOrdAdminListReq) Reset() {
	*x = VirtOrdAdminListReq{}
	mi := &file_account_remote_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtOrdAdminListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrdAdminListReq) ProtoMessage() {}

func (x *VirtOrdAdminListReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrdAdminListReq.ProtoReflect.Descriptor instead.
func (*VirtOrdAdminListReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{17}
}

func (x *VirtOrdAdminListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VirtOrdAdminListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *VirtOrdAdminListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VirtOrdAdminRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTs     int64                  `protobuf:"varint,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Items         map[int32]int64        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	UpTs          int64                  `protobuf:"varint,8,opt,name=up_ts,json=upTs,proto3" json:"up_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtOrdAdminRow) Reset() {
	*x = VirtOrdAdminRow{}
	mi := &file_account_remote_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtOrdAdminRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrdAdminRow) ProtoMessage() {}

func (x *VirtOrdAdminRow) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrdAdminRow.ProtoReflect.Descriptor instead.
func (*VirtOrdAdminRow) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{18}
}

func (x *VirtOrdAdminRow) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtOrdAdminRow) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VirtOrdAdminRow) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VirtOrdAdminRow) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *VirtOrdAdminRow) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *VirtOrdAdminRow) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VirtOrdAdminRow) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *VirtOrdAdminRow) GetUpTs() int64 {
	if x != nil {
		return x.UpTs
	}
	return 0
}

type VirtOrdAdminListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*VirtOrdAdminRow     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtOrdAdminListAck) Reset() {
	*x = VirtOrdAdminListAck{}
	mi := &file_account_remote_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtOrdAdminListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrdAdminListAck) ProtoMessage() {}

func (x *VirtOrdAdminListAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrdAdminListAck.ProtoReflect.Descriptor instead.
func (*VirtOrdAdminListAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{19}
}

func (x *VirtOrdAdminListAck) GetRows() []*VirtOrdAdminRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *VirtOrdAdminListAck) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 运营改状态（内部 RPC）：待处理 -> 已完成/已取消
type VirtOrdMarkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	St            int32                  `protobuf:"varint,2,opt,name=st,proto3" json:"st,omitempty"` // 2已完成 3已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtOrdMarkReq) Reset() {
	*x = VirtOrdMarkReq{}
	mi := &file_account_remote_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtOrdMarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrdMarkReq) ProtoMessage() {}

func (x *VirtOrdMarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrdMarkReq.ProtoReflect.Descriptor instead.
func (*VirtOrdMarkReq) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{20}
}

func (x *VirtOrdMarkReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtOrdMarkReq) GetSt() int32 {
	if x != nil {
		return x.St
	}
	return 0
}

type VirtOrdMarkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtOrdMarkAck) Reset() {
	*x = VirtOrdMarkAck{}
	mi := &file_account_remote_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtOrdMarkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtOrdMarkAck) ProtoMessage() {}

func (x *VirtOrdMarkAck) ProtoReflect() protoreflect.Message {
	mi := &file_account_remote_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtOrdMarkAck.ProtoReflect.Descriptor instead.
func (*VirtOrdMarkAck) Descriptor() ([]byte, []int) {
	return file_account_remote_proto_rawDescGZIP(), []int{21}
}

var File_account_remote_proto protoreflect.FileDescriptor

const file_account_remote_proto_rawDesc = "" +
	"\n" +
	"\x14account_remote.proto\x12\x06sproto\x1a\x19google/protobuf/any.proto\"F\n" +
	"\n" +
	"AccountReq\x12\x10\n" +
	"\x03bot\x18\x01 \x01(\bR\x03bot\x12&\n" +
	"\x03req\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03req\"F\n" +
	"\n" +
	"AccountAck\x12\x10\n" +
	"\x03bot\x18\x01 \x01(\bR\x03bot\x12&\n" +
	"\x03ack\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03ack\"\v\n" +
	"\tGetBotReq\"7\n" +
	"\tGetBotAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x18\n" +
	"\aexpired\x18\x02 \x01(\x03R\aexpired\"!\n" +
	"\rPlayerInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\xc7\x01\n" +
	"\rPlayerInfoAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x126\n" +
	"\x05items\x18\x04 \x03(\v2 .sproto.PlayerInfoAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x95\x01\n" +
	"\x0eChangeItemsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.sproto.ChangeItemsReq.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x95\x01\n" +
	"\x0eChangeItemsAck\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.sproto.ChangeItemsAck.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"%\n" +
	"\x11GetNewbieStatsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"y\n" +
	"\x11GetNewbieStatsAck\x12\x1f\n" +
	"\vmatch_count\x18\x01 \x01(\x05R\n" +
	"matchCount\x12\x1a\n" +
	"\bpressure\x18\x02 \x01(\x05R\bpressure\x12'\n" +
	"\x0fprotected_count\x18\x03 \x01(\x05R\x0eprotectedCount\"f\n" +
	"\x14UpdateNewbieStatsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03win\x18\x02 \x01(\bR\x03win\x12*\n" +
	"\x11in_protected_room\x18\x03 \x01(\bR\x0finProtectedRoom\"\x16\n" +
	"\x14UpdateNewbieStatsAck\"f\n" +
	"\x0ePhysOrdShipReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02st\x18\x02 \x01(\x05R\x02st\x12\x1b\n" +
	"\texpr_corp\x18\x03 \x01(\tR\bexprCorp\x12\x17\n" +
	"\aexpr_no\x18\x04 \x01(\tR\x06exprNo\"\x10\n" +
	"\x0ePhysOrdShipAck\"U\n" +
	"\x13PhysOrdAdminListReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\x88\x03\n" +
	"\x0fPhysOrdAdminRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x04 \x01(\x03R\tcreatedTs\x128\n" +
	"\x05items\x18\x05 \x03(\v2\".sproto.PhysOrdAdminRow.ItemsEntryR\x05items\x12\x1b\n" +
	"\trecv_name\x18\x06 \x01(\tR\brecvName\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x12\n" +
	"\x04addr\x18\b \x01(\tR\x04addr\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1b\n" +
	"\texpr_corp\x18\n" +
	" \x01(\tR\bexprCorp\x12\x17\n" +
	"\aexpr_no\x18\v \x01(\tR\x06exprNo\x12\x13\n" +
	"\x05up_ts\x18\f \x01(\x03R\x04upTs\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"X\n" +
	"\x13PhysOrdAdminListAck\x12+\n" +
	"\x04rows\x18\x01 \x03(\v2\x17.sproto.PhysOrdAdminRowR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\x13VirtOrdAdminListReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xa1\x02\n" +
	"\x0fVirtOrdAdminRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_ts\x18\x04 \x01(\x03R\tcreatedTs\x128\n" +
	"\x05items\x18\x05 \x03(\v2\".sproto.VirtOrdAdminRow.ItemsEntryR\x05items\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12\x13\n" +
	"\x05up_ts\x18\b \x01(\x03R\x04upTs\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"X\n" +
	"\x13VirtOrdAdminListAck\x12+\n" +
	"\x04rows\x18\x01 \x03(\v2\x17.sproto.VirtOrdAdminRowR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"0\n" +
	"\x0eVirtOrdMarkReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02st\x18\x02 \x01(\x05R\x02st\"\x10\n" +
	"\x0eVirtOrdMarkAckB\vZ\t../sprotob\x06proto3"

var (
	file_account_remote_proto_rawDescOnce sync.Once
	file_account_remote_proto_rawDescData []byte
)

func file_account_remote_proto_rawDescGZIP() []byte {
	file_account_remote_proto_rawDescOnce.Do(func() {
		file_account_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_remote_proto_rawDesc), len(file_account_remote_proto_rawDesc)))
	})
	return file_account_remote_proto_rawDescData
}

var file_account_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_account_remote_proto_goTypes = []any{
	(*AccountReq)(nil),           // 0: sproto.AccountReq
	(*AccountAck)(nil),           // 1: sproto.AccountAck
	(*GetBotReq)(nil),            // 2: sproto.GetBotReq
	(*GetBotAck)(nil),            // 3: sproto.GetBotAck
	(*PlayerInfoReq)(nil),        // 4: sproto.PlayerInfoReq
	(*PlayerInfoAck)(nil),        // 5: sproto.PlayerInfoAck
	(*ChangeItemsReq)(nil),       // 6: sproto.ChangeItemsReq
	(*ChangeItemsAck)(nil),       // 7: sproto.ChangeItemsAck
	(*GetNewbieStatsReq)(nil),    // 8: sproto.GetNewbieStatsReq
	(*GetNewbieStatsAck)(nil),    // 9: sproto.GetNewbieStatsAck
	(*UpdateNewbieStatsReq)(nil), // 10: sproto.UpdateNewbieStatsReq
	(*UpdateNewbieStatsAck)(nil), // 11: sproto.UpdateNewbieStatsAck
	(*PhysOrdShipReq)(nil),       // 12: sproto.PhysOrdShipReq
	(*PhysOrdShipAck)(nil),       // 13: sproto.PhysOrdShipAck
	(*PhysOrdAdminListReq)(nil),  // 14: sproto.PhysOrdAdminListReq
	(*PhysOrdAdminRow)(nil),      // 15: sproto.PhysOrdAdminRow
	(*PhysOrdAdminListAck)(nil),  // 16: sproto.PhysOrdAdminListAck
	(*VirtOrdAdminListReq)(nil),  // 17: sproto.VirtOrdAdminListReq
	(*VirtOrdAdminRow)(nil),      // 18: sproto.VirtOrdAdminRow
	(*VirtOrdAdminListAck)(nil),  // 19: sproto.VirtOrdAdminListAck
	(*VirtOrdMarkReq)(nil),       // 20: sproto.VirtOrdMarkReq
	(*VirtOrdMarkAck)(nil),       // 21: sproto.VirtOrdMarkAck
	nil,                          // 22: sproto.PlayerInfoAck.ItemsEntry
	nil,                          // 23: sproto.ChangeItemsReq.ItemsEntry
	nil,                          // 24: sproto.ChangeItemsAck.ItemsEntry
	nil,                          // 25: sproto.PhysOrdAdminRow.ItemsEntry
	nil,                          // 26: sproto.VirtOrdAdminRow.ItemsEntry
	(*anypb.Any)(nil),            // 27: google.protobuf.Any
}
var file_account_remote_proto_depIdxs = []int32{
	27, // 0: sproto.AccountReq.req:type_name -> google.protobuf.Any
	27, // 1: sproto.AccountAck.ack:type_name -> google.protobuf.Any
	22, // 2: sproto.PlayerInfoAck.items:type_name -> sproto.PlayerInfoAck.ItemsEntry
	23, // 3: sproto.ChangeItemsReq.items:type_name -> sproto.ChangeItemsReq.ItemsEntry
	24, // 4: sproto.ChangeItemsAck.items:type_name -> sproto.ChangeItemsAck.ItemsEntry
	25, // 5: sproto.PhysOrdAdminRow.items:type_name -> sproto.PhysOrdAdminRow.ItemsEntry
	15, // 6: sproto.PhysOrdAdminListAck.rows:type_name -> sproto.PhysOrdAdminRow
	26, // 7: sproto.VirtOrdAdminRow.items:type_name -> sproto.VirtOrdAdminRow.ItemsEntry
	18, // 8: sproto.VirtOrdAdminListAck.rows:type_name -> sproto.VirtOrdAdminRow
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_account_remote_proto_init() }
func file_account_remote_proto_init() {
	if File_account_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_remote_proto_rawDesc), len(file_account_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_remote_proto_goTypes,
		DependencyIndexes: file_account_remote_proto_depIdxs,
		MessageInfos:      file_account_remote_proto_msgTypes,
	}.Build()
	File_account_remote_proto = out.File
	file_account_remote_proto_goTypes = nil
	file_account_remote_proto_depIdxs = nil
}
