// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: matchcfg_remote.proto

package sproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchCfgVersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    string                 `protobuf:"bytes,1,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"` // island/fdtable/schedule/wheel, empty means all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgVersionReq) Reset() {
	*x = MatchCfgVersionReq{}
	mi := &file_matchcfg_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgVersionReq) ProtoMessage() {}

func (x *MatchCfgVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgVersionReq.ProtoReflect.Descriptor instead.
func (*MatchCfgVersionReq) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{0}
}

func (x *MatchCfgVersionReq) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

type MatchCfgVersionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // max(version) within scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgVersionAck) Reset() {
	*x = MatchCfgVersionAck{}
	mi := &file_matchcfg_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgVersionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgVersionAck) ProtoMessage() {}

func (x *MatchCfgVersionAck) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgVersionAck.ProtoReflect.Descriptor instead.
func (*MatchCfgVersionAck) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{1}
}

func (x *MatchCfgVersionAck) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MatchCfgRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    string                 `protobuf:"bytes,1,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	MatchId       int32                  `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // YAML
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	GameType      string                 `protobuf:"bytes,6,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	PlacementIps  string                 `protobuf:"bytes,7,opt,name=placement_ips,json=placementIps,proto3" json:"placement_ips,omitempty"` // JSON array string, e.g. ["10.0.1.3","10.0.1.4"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgRow) Reset() {
	*x = MatchCfgRow{}
	mi := &file_matchcfg_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgRow) ProtoMessage() {}

func (x *MatchCfgRow) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgRow.ProtoReflect.Descriptor instead.
func (*MatchCfgRow) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{2}
}

func (x *MatchCfgRow) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *MatchCfgRow) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *MatchCfgRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchCfgRow) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MatchCfgRow) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MatchCfgRow) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *MatchCfgRow) GetPlacementIps() string {
	if x != nil {
		return x.PlacementIps
	}
	return ""
}

type MatchCfgListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    string                 `protobuf:"bytes,1,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"` // required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgListReq) Reset() {
	*x = MatchCfgListReq{}
	mi := &file_matchcfg_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgListReq) ProtoMessage() {}

func (x *MatchCfgListReq) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgListReq.ProtoReflect.Descriptor instead.
func (*MatchCfgListReq) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{3}
}

func (x *MatchCfgListReq) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

type MatchCfgListAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*MatchCfgRow         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgListAck) Reset() {
	*x = MatchCfgListAck{}
	mi := &file_matchcfg_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgListAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgListAck) ProtoMessage() {}

func (x *MatchCfgListAck) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgListAck.ProtoReflect.Descriptor instead.
func (*MatchCfgListAck) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{4}
}

func (x *MatchCfgListAck) GetRows() []*MatchCfgRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type MatchCfgGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerType    string                 `protobuf:"bytes,1,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	MatchId       int32                  `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgGetReq) Reset() {
	*x = MatchCfgGetReq{}
	mi := &file_matchcfg_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgGetReq) ProtoMessage() {}

func (x *MatchCfgGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgGetReq.ProtoReflect.Descriptor instead.
func (*MatchCfgGetReq) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{5}
}

func (x *MatchCfgGetReq) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *MatchCfgGetReq) GetMatchId() int32 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type MatchCfgGetAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *MatchCfgRow           `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCfgGetAck) Reset() {
	*x = MatchCfgGetAck{}
	mi := &file_matchcfg_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCfgGetAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCfgGetAck) ProtoMessage() {}

func (x *MatchCfgGetAck) ProtoReflect() protoreflect.Message {
	mi := &file_matchcfg_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCfgGetAck.ProtoReflect.Descriptor instead.
func (*MatchCfgGetAck) Descriptor() ([]byte, []int) {
	return file_matchcfg_remote_proto_rawDescGZIP(), []int{6}
}

func (x *MatchCfgGetAck) GetRow() *MatchCfgRow {
	if x != nil {
		return x.Row
	}
	return nil
}

var File_matchcfg_remote_proto protoreflect.FileDescriptor

const file_matchcfg_remote_proto_rawDesc = "" +
	"\n" +
	"\x15matchcfg_remote.proto\x12\x06sproto\"5\n" +
	"\x12MatchCfgVersionReq\x12\x1f\n" +
	"\vserver_type\x18\x01 \x01(\tR\n" +
	"serverType\".\n" +
	"\x12MatchCfgVersionAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\xd3\x01\n" +
	"\vMatchCfgRow\x12\x1f\n" +
	"\vserver_type\x18\x01 \x01(\tR\n" +
	"serverType\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x05R\amatchId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12\x1b\n" +
	"\tgame_type\x18\x06 \x01(\tR\bgameType\x12#\n" +
	"\rplacement_ips\x18\a \x01(\tR\fplacementIps\"2\n" +
	"\x0fMatchCfgListReq\x12\x1f\n" +
	"\vserver_type\x18\x01 \x01(\tR\n" +
	"serverType\":\n" +
	"\x0fMatchCfgListAck\x12'\n" +
	"\x04rows\x18\x01 \x03(\v2\x13.sproto.MatchCfgRowR\x04rows\"L\n" +
	"\x0eMatchCfgGetReq\x12\x1f\n" +
	"\vserver_type\x18\x01 \x01(\tR\n" +
	"serverType\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\x05R\amatchId\"7\n" +
	"\x0eMatchCfgGetAck\x12%\n" +
	"\x03row\x18\x01 \x01(\v2\x13.sproto.MatchCfgRowR\x03rowB\vZ\t../sprotob\x06proto3"

var (
	file_matchcfg_remote_proto_rawDescOnce sync.Once
	file_matchcfg_remote_proto_rawDescData []byte
)

func file_matchcfg_remote_proto_rawDescGZIP() []byte {
	file_matchcfg_remote_proto_rawDescOnce.Do(func() {
		file_matchcfg_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchcfg_remote_proto_rawDesc), len(file_matchcfg_remote_proto_rawDesc)))
	})
	return file_matchcfg_remote_proto_rawDescData
}

var file_matchcfg_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_matchcfg_remote_proto_goTypes = []any{
	(*MatchCfgVersionReq)(nil), // 0: sproto.MatchCfgVersionReq
	(*MatchCfgVersionAck)(nil), // 1: sproto.MatchCfgVersionAck
	(*MatchCfgRow)(nil),        // 2: sproto.MatchCfgRow
	(*MatchCfgListReq)(nil),    // 3: sproto.MatchCfgListReq
	(*MatchCfgListAck)(nil),    // 4: sproto.MatchCfgListAck
	(*MatchCfgGetReq)(nil),     // 5: sproto.MatchCfgGetReq
	(*MatchCfgGetAck)(nil),     // 6: sproto.MatchCfgGetAck
}
var file_matchcfg_remote_proto_depIdxs = []int32{
	2, // 0: sproto.MatchCfgListAck.rows:type_name -> sproto.MatchCfgRow
	2, // 1: sproto.MatchCfgGetAck.row:type_name -> sproto.MatchCfgRow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matchcfg_remote_proto_init() }
func file_matchcfg_remote_proto_init() {
	if File_matchcfg_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchcfg_remote_proto_rawDesc), len(file_matchcfg_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchcfg_remote_proto_goTypes,
		DependencyIndexes: file_matchcfg_remote_proto_depIdxs,
		MessageInfos:      file_matchcfg_remote_proto_msgTypes,
	}.Build()
	File_matchcfg_remote_proto = out.File
	file_matchcfg_remote_proto_goTypes = nil
	file_matchcfg_remote_proto_depIdxs = nil
}
