// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_activity_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_activity_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_activity_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_activity_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_activity_2eproto;
namespace cproto {
class ActBrief;
struct ActBriefDefaultTypeInternal;
extern ActBriefDefaultTypeInternal _ActBrief_default_instance_;
class ActPanelAck;
struct ActPanelAckDefaultTypeInternal;
extern ActPanelAckDefaultTypeInternal _ActPanelAck_default_instance_;
class ActPanelReq;
struct ActPanelReqDefaultTypeInternal;
extern ActPanelReqDefaultTypeInternal _ActPanelReq_default_instance_;
class ActRewardAck;
struct ActRewardAckDefaultTypeInternal;
extern ActRewardAckDefaultTypeInternal _ActRewardAck_default_instance_;
class ActRewardReq;
struct ActRewardReqDefaultTypeInternal;
extern ActRewardReqDefaultTypeInternal _ActRewardReq_default_instance_;
class ActivityAck;
struct ActivityAckDefaultTypeInternal;
extern ActivityAckDefaultTypeInternal _ActivityAck_default_instance_;
class ActivityReq;
struct ActivityReqDefaultTypeInternal;
extern ActivityReqDefaultTypeInternal _ActivityReq_default_instance_;
class ActsListAck;
struct ActsListAckDefaultTypeInternal;
extern ActsListAckDefaultTypeInternal _ActsListAck_default_instance_;
class ActsListReq;
struct ActsListReqDefaultTypeInternal;
extern ActsListReqDefaultTypeInternal _ActsListReq_default_instance_;
}  // namespace cproto
PROTOBUF_NAMESPACE_OPEN
template<> ::cproto::ActBrief* Arena::CreateMaybeMessage<::cproto::ActBrief>(Arena*);
template<> ::cproto::ActPanelAck* Arena::CreateMaybeMessage<::cproto::ActPanelAck>(Arena*);
template<> ::cproto::ActPanelReq* Arena::CreateMaybeMessage<::cproto::ActPanelReq>(Arena*);
template<> ::cproto::ActRewardAck* Arena::CreateMaybeMessage<::cproto::ActRewardAck>(Arena*);
template<> ::cproto::ActRewardReq* Arena::CreateMaybeMessage<::cproto::ActRewardReq>(Arena*);
template<> ::cproto::ActivityAck* Arena::CreateMaybeMessage<::cproto::ActivityAck>(Arena*);
template<> ::cproto::ActivityReq* Arena::CreateMaybeMessage<::cproto::ActivityReq>(Arena*);
template<> ::cproto::ActsListAck* Arena::CreateMaybeMessage<::cproto::ActsListAck>(Arena*);
template<> ::cproto::ActsListReq* Arena::CreateMaybeMessage<::cproto::ActsListReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cproto {

// ===================================================================

class ActivityReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActivityReq) */ {
 public:
  inline ActivityReq() : ActivityReq(nullptr) {}
  ~ActivityReq() override;
  explicit constexpr ActivityReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActivityReq(const ActivityReq& from);
  ActivityReq(ActivityReq&& from) noexcept
    : ActivityReq() {
    *this = ::std::move(from);
  }

  inline ActivityReq& operator=(const ActivityReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActivityReq& operator=(ActivityReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActivityReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActivityReq* internal_default_instance() {
    return reinterpret_cast<const ActivityReq*>(
               &_ActivityReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ActivityReq& a, ActivityReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ActivityReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActivityReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActivityReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActivityReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActivityReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActivityReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActivityReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActivityReq";
  }
  protected:
  explicit ActivityReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqFieldNumber = 1,
  };
  // .google.protobuf.Any req = 1;
  bool has_req() const;
  private:
  bool _internal_has_req() const;
  public:
  void clear_req();
  const ::PROTOBUF_NAMESPACE_ID::Any& req() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_req();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_req();
  void set_allocated_req(::PROTOBUF_NAMESPACE_ID::Any* req);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_req() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_req();
  public:
  void unsafe_arena_set_allocated_req(
      ::PROTOBUF_NAMESPACE_ID::Any* req);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_req();

  // @@protoc_insertion_point(class_scope:cproto.ActivityReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::Any* req_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActivityAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActivityAck) */ {
 public:
  inline ActivityAck() : ActivityAck(nullptr) {}
  ~ActivityAck() override;
  explicit constexpr ActivityAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActivityAck(const ActivityAck& from);
  ActivityAck(ActivityAck&& from) noexcept
    : ActivityAck() {
    *this = ::std::move(from);
  }

  inline ActivityAck& operator=(const ActivityAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActivityAck& operator=(ActivityAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActivityAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActivityAck* internal_default_instance() {
    return reinterpret_cast<const ActivityAck*>(
               &_ActivityAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ActivityAck& a, ActivityAck& b) {
    a.Swap(&b);
  }
  inline void Swap(ActivityAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActivityAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActivityAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActivityAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActivityAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActivityAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActivityAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActivityAck";
  }
  protected:
  explicit ActivityAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAckFieldNumber = 1,
  };
  // .google.protobuf.Any ack = 1;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;
  public:
  void clear_ack();
  const ::PROTOBUF_NAMESPACE_ID::Any& ack() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_ack();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_ack();
  void set_allocated_ack(::PROTOBUF_NAMESPACE_ID::Any* ack);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_ack() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_ack();
  public:
  void unsafe_arena_set_allocated_ack(
      ::PROTOBUF_NAMESPACE_ID::Any* ack);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_ack();

  // @@protoc_insertion_point(class_scope:cproto.ActivityAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::Any* ack_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActsListReq final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:cproto.ActsListReq) */ {
 public:
  inline ActsListReq() : ActsListReq(nullptr) {}
  explicit constexpr ActsListReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActsListReq(const ActsListReq& from);
  ActsListReq(ActsListReq&& from) noexcept
    : ActsListReq() {
    *this = ::std::move(from);
  }

  inline ActsListReq& operator=(const ActsListReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActsListReq& operator=(ActsListReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActsListReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActsListReq* internal_default_instance() {
    return reinterpret_cast<const ActsListReq*>(
               &_ActsListReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ActsListReq& a, ActsListReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ActsListReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActsListReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActsListReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActsListReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ActsListReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ActsListReq& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActsListReq";
  }
  protected:
  explicit ActsListReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cproto.ActsListReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActsListAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActsListAck) */ {
 public:
  inline ActsListAck() : ActsListAck(nullptr) {}
  ~ActsListAck() override;
  explicit constexpr ActsListAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActsListAck(const ActsListAck& from);
  ActsListAck(ActsListAck&& from) noexcept
    : ActsListAck() {
    *this = ::std::move(from);
  }

  inline ActsListAck& operator=(const ActsListAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActsListAck& operator=(ActsListAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActsListAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActsListAck* internal_default_instance() {
    return reinterpret_cast<const ActsListAck*>(
               &_ActsListAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ActsListAck& a, ActsListAck& b) {
    a.Swap(&b);
  }
  inline void Swap(ActsListAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActsListAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActsListAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActsListAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActsListAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActsListAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActsListAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActsListAck";
  }
  protected:
  explicit ActsListAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActsFieldNumber = 2,
    kRedDotFieldNumber = 1,
  };
  // repeated .cproto.ActBrief acts = 2;
  int acts_size() const;
  private:
  int _internal_acts_size() const;
  public:
  void clear_acts();
  ::cproto::ActBrief* mutable_acts(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cproto::ActBrief >*
      mutable_acts();
  private:
  const ::cproto::ActBrief& _internal_acts(int index) const;
  ::cproto::ActBrief* _internal_add_acts();
  public:
  const ::cproto::ActBrief& acts(int index) const;
  ::cproto::ActBrief* add_acts();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cproto::ActBrief >&
      acts() const;

  // bool red_dot = 1;
  void clear_red_dot();
  bool red_dot() const;
  void set_red_dot(bool value);
  private:
  bool _internal_red_dot() const;
  void _internal_set_red_dot(bool value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActsListAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cproto::ActBrief > acts_;
  bool red_dot_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActPanelReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActPanelReq) */ {
 public:
  inline ActPanelReq() : ActPanelReq(nullptr) {}
  ~ActPanelReq() override;
  explicit constexpr ActPanelReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActPanelReq(const ActPanelReq& from);
  ActPanelReq(ActPanelReq&& from) noexcept
    : ActPanelReq() {
    *this = ::std::move(from);
  }

  inline ActPanelReq& operator=(const ActPanelReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActPanelReq& operator=(ActPanelReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActPanelReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActPanelReq* internal_default_instance() {
    return reinterpret_cast<const ActPanelReq*>(
               &_ActPanelReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ActPanelReq& a, ActPanelReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ActPanelReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActPanelReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActPanelReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActPanelReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActPanelReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActPanelReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActPanelReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActPanelReq";
  }
  protected:
  explicit ActPanelReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActivityIdFieldNumber = 1,
  };
  // int32 activity_id = 1;
  void clear_activity_id();
  int32_t activity_id() const;
  void set_activity_id(int32_t value);
  private:
  int32_t _internal_activity_id() const;
  void _internal_set_activity_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActPanelReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t activity_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActPanelAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActPanelAck) */ {
 public:
  inline ActPanelAck() : ActPanelAck(nullptr) {}
  ~ActPanelAck() override;
  explicit constexpr ActPanelAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActPanelAck(const ActPanelAck& from);
  ActPanelAck(ActPanelAck&& from) noexcept
    : ActPanelAck() {
    *this = ::std::move(from);
  }

  inline ActPanelAck& operator=(const ActPanelAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActPanelAck& operator=(ActPanelAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActPanelAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActPanelAck* internal_default_instance() {
    return reinterpret_cast<const ActPanelAck*>(
               &_ActPanelAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ActPanelAck& a, ActPanelAck& b) {
    a.Swap(&b);
  }
  inline void Swap(ActPanelAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActPanelAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActPanelAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActPanelAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActPanelAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActPanelAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActPanelAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActPanelAck";
  }
  protected:
  explicit ActPanelAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJsonDataFieldNumber = 2,
    kActivityIdFieldNumber = 1,
  };
  // string json_data = 2;
  void clear_json_data();
  const std::string& json_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_json_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_json_data();
  PROTOBUF_NODISCARD std::string* release_json_data();
  void set_allocated_json_data(std::string* json_data);
  private:
  const std::string& _internal_json_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json_data(const std::string& value);
  std::string* _internal_mutable_json_data();
  public:

  // int32 activity_id = 1;
  void clear_activity_id();
  int32_t activity_id() const;
  void set_activity_id(int32_t value);
  private:
  int32_t _internal_activity_id() const;
  void _internal_set_activity_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActPanelAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_data_;
  int32_t activity_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActRewardReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActRewardReq) */ {
 public:
  inline ActRewardReq() : ActRewardReq(nullptr) {}
  ~ActRewardReq() override;
  explicit constexpr ActRewardReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActRewardReq(const ActRewardReq& from);
  ActRewardReq(ActRewardReq&& from) noexcept
    : ActRewardReq() {
    *this = ::std::move(from);
  }

  inline ActRewardReq& operator=(const ActRewardReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActRewardReq& operator=(ActRewardReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActRewardReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActRewardReq* internal_default_instance() {
    return reinterpret_cast<const ActRewardReq*>(
               &_ActRewardReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ActRewardReq& a, ActRewardReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ActRewardReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActRewardReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActRewardReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActRewardReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActRewardReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActRewardReq& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActRewardReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActRewardReq";
  }
  protected:
  explicit ActRewardReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJsonDataFieldNumber = 2,
    kActivityIdFieldNumber = 1,
  };
  // string json_data = 2;
  void clear_json_data();
  const std::string& json_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_json_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_json_data();
  PROTOBUF_NODISCARD std::string* release_json_data();
  void set_allocated_json_data(std::string* json_data);
  private:
  const std::string& _internal_json_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json_data(const std::string& value);
  std::string* _internal_mutable_json_data();
  public:

  // int32 activity_id = 1;
  void clear_activity_id();
  int32_t activity_id() const;
  void set_activity_id(int32_t value);
  private:
  int32_t _internal_activity_id() const;
  void _internal_set_activity_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActRewardReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_data_;
  int32_t activity_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActRewardAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActRewardAck) */ {
 public:
  inline ActRewardAck() : ActRewardAck(nullptr) {}
  ~ActRewardAck() override;
  explicit constexpr ActRewardAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActRewardAck(const ActRewardAck& from);
  ActRewardAck(ActRewardAck&& from) noexcept
    : ActRewardAck() {
    *this = ::std::move(from);
  }

  inline ActRewardAck& operator=(const ActRewardAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActRewardAck& operator=(ActRewardAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActRewardAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActRewardAck* internal_default_instance() {
    return reinterpret_cast<const ActRewardAck*>(
               &_ActRewardAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ActRewardAck& a, ActRewardAck& b) {
    a.Swap(&b);
  }
  inline void Swap(ActRewardAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActRewardAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActRewardAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActRewardAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActRewardAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActRewardAck& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActRewardAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActRewardAck";
  }
  protected:
  explicit ActRewardAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJsonDataFieldNumber = 2,
    kActivityIdFieldNumber = 1,
  };
  // string json_data = 2;
  void clear_json_data();
  const std::string& json_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_json_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_json_data();
  PROTOBUF_NODISCARD std::string* release_json_data();
  void set_allocated_json_data(std::string* json_data);
  private:
  const std::string& _internal_json_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json_data(const std::string& value);
  std::string* _internal_mutable_json_data();
  public:

  // int32 activity_id = 1;
  void clear_activity_id();
  int32_t activity_id() const;
  void set_activity_id(int32_t value);
  private:
  int32_t _internal_activity_id() const;
  void _internal_set_activity_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActRewardAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_data_;
  int32_t activity_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// -------------------------------------------------------------------

class ActBrief final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cproto.ActBrief) */ {
 public:
  inline ActBrief() : ActBrief(nullptr) {}
  ~ActBrief() override;
  explicit constexpr ActBrief(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActBrief(const ActBrief& from);
  ActBrief(ActBrief&& from) noexcept
    : ActBrief() {
    *this = ::std::move(from);
  }

  inline ActBrief& operator=(const ActBrief& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActBrief& operator=(ActBrief&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActBrief& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActBrief* internal_default_instance() {
    return reinterpret_cast<const ActBrief*>(
               &_ActBrief_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(ActBrief& a, ActBrief& b) {
    a.Swap(&b);
  }
  inline void Swap(ActBrief* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActBrief* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActBrief* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActBrief>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActBrief& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ActBrief& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActBrief* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cproto.ActBrief";
  }
  protected:
  explicit ActBrief(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kActivityIdFieldNumber = 1,
    kStatusFieldNumber = 3,
    kEndTsFieldNumber = 4,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 activity_id = 1;
  void clear_activity_id();
  int32_t activity_id() const;
  void set_activity_id(int32_t value);
  private:
  int32_t _internal_activity_id() const;
  void _internal_set_activity_id(int32_t value);
  public:

  // int32 status = 3;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // int64 end_ts = 4;
  void clear_end_ts();
  int64_t end_ts() const;
  void set_end_ts(int64_t value);
  private:
  int64_t _internal_end_ts() const;
  void _internal_set_end_ts(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:cproto.ActBrief)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  int32_t activity_id_;
  int32_t status_;
  int64_t end_ts_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_activity_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ActivityReq

// .google.protobuf.Any req = 1;
inline bool ActivityReq::_internal_has_req() const {
  return this != internal_default_instance() && req_ != nullptr;
}
inline bool ActivityReq::has_req() const {
  return _internal_has_req();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& ActivityReq::_internal_req() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = req_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& ActivityReq::req() const {
  // @@protoc_insertion_point(field_get:cproto.ActivityReq.req)
  return _internal_req();
}
inline void ActivityReq::unsafe_arena_set_allocated_req(
    ::PROTOBUF_NAMESPACE_ID::Any* req) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(req_);
  }
  req_ = req;
  if (req) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cproto.ActivityReq.req)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityReq::release_req() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = req_;
  req_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityReq::unsafe_arena_release_req() {
  // @@protoc_insertion_point(field_release:cproto.ActivityReq.req)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = req_;
  req_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityReq::_internal_mutable_req() {
  
  if (req_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    req_ = p;
  }
  return req_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityReq::mutable_req() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_req();
  // @@protoc_insertion_point(field_mutable:cproto.ActivityReq.req)
  return _msg;
}
inline void ActivityReq::set_allocated_req(::PROTOBUF_NAMESPACE_ID::Any* req) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(req_);
  }
  if (req) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(req));
    if (message_arena != submessage_arena) {
      req = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, req, submessage_arena);
    }
    
  } else {
    
  }
  req_ = req;
  // @@protoc_insertion_point(field_set_allocated:cproto.ActivityReq.req)
}

// -------------------------------------------------------------------

// ActivityAck

// .google.protobuf.Any ack = 1;
inline bool ActivityAck::_internal_has_ack() const {
  return this != internal_default_instance() && ack_ != nullptr;
}
inline bool ActivityAck::has_ack() const {
  return _internal_has_ack();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& ActivityAck::_internal_ack() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = ack_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& ActivityAck::ack() const {
  // @@protoc_insertion_point(field_get:cproto.ActivityAck.ack)
  return _internal_ack();
}
inline void ActivityAck::unsafe_arena_set_allocated_ack(
    ::PROTOBUF_NAMESPACE_ID::Any* ack) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ack_);
  }
  ack_ = ack;
  if (ack) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cproto.ActivityAck.ack)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityAck::release_ack() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = ack_;
  ack_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityAck::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_release:cproto.ActivityAck.ack)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = ack_;
  ack_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityAck::_internal_mutable_ack() {
  
  if (ack_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    ack_ = p;
  }
  return ack_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* ActivityAck::mutable_ack() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:cproto.ActivityAck.ack)
  return _msg;
}
inline void ActivityAck::set_allocated_ack(::PROTOBUF_NAMESPACE_ID::Any* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(ack_);
  }
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ack));
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    
  } else {
    
  }
  ack_ = ack;
  // @@protoc_insertion_point(field_set_allocated:cproto.ActivityAck.ack)
}

// -------------------------------------------------------------------

// ActsListReq

// -------------------------------------------------------------------

// ActsListAck

// bool red_dot = 1;
inline void ActsListAck::clear_red_dot() {
  red_dot_ = false;
}
inline bool ActsListAck::_internal_red_dot() const {
  return red_dot_;
}
inline bool ActsListAck::red_dot() const {
  // @@protoc_insertion_point(field_get:cproto.ActsListAck.red_dot)
  return _internal_red_dot();
}
inline void ActsListAck::_internal_set_red_dot(bool value) {
  
  red_dot_ = value;
}
inline void ActsListAck::set_red_dot(bool value) {
  _internal_set_red_dot(value);
  // @@protoc_insertion_point(field_set:cproto.ActsListAck.red_dot)
}

// repeated .cproto.ActBrief acts = 2;
inline int ActsListAck::_internal_acts_size() const {
  return acts_.size();
}
inline int ActsListAck::acts_size() const {
  return _internal_acts_size();
}
inline void ActsListAck::clear_acts() {
  acts_.Clear();
}
inline ::cproto::ActBrief* ActsListAck::mutable_acts(int index) {
  // @@protoc_insertion_point(field_mutable:cproto.ActsListAck.acts)
  return acts_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cproto::ActBrief >*
ActsListAck::mutable_acts() {
  // @@protoc_insertion_point(field_mutable_list:cproto.ActsListAck.acts)
  return &acts_;
}
inline const ::cproto::ActBrief& ActsListAck::_internal_acts(int index) const {
  return acts_.Get(index);
}
inline const ::cproto::ActBrief& ActsListAck::acts(int index) const {
  // @@protoc_insertion_point(field_get:cproto.ActsListAck.acts)
  return _internal_acts(index);
}
inline ::cproto::ActBrief* ActsListAck::_internal_add_acts() {
  return acts_.Add();
}
inline ::cproto::ActBrief* ActsListAck::add_acts() {
  ::cproto::ActBrief* _add = _internal_add_acts();
  // @@protoc_insertion_point(field_add:cproto.ActsListAck.acts)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cproto::ActBrief >&
ActsListAck::acts() const {
  // @@protoc_insertion_point(field_list:cproto.ActsListAck.acts)
  return acts_;
}

// -------------------------------------------------------------------

// ActPanelReq

// int32 activity_id = 1;
inline void ActPanelReq::clear_activity_id() {
  activity_id_ = 0;
}
inline int32_t ActPanelReq::_internal_activity_id() const {
  return activity_id_;
}
inline int32_t ActPanelReq::activity_id() const {
  // @@protoc_insertion_point(field_get:cproto.ActPanelReq.activity_id)
  return _internal_activity_id();
}
inline void ActPanelReq::_internal_set_activity_id(int32_t value) {
  
  activity_id_ = value;
}
inline void ActPanelReq::set_activity_id(int32_t value) {
  _internal_set_activity_id(value);
  // @@protoc_insertion_point(field_set:cproto.ActPanelReq.activity_id)
}

// -------------------------------------------------------------------

// ActPanelAck

// int32 activity_id = 1;
inline void ActPanelAck::clear_activity_id() {
  activity_id_ = 0;
}
inline int32_t ActPanelAck::_internal_activity_id() const {
  return activity_id_;
}
inline int32_t ActPanelAck::activity_id() const {
  // @@protoc_insertion_point(field_get:cproto.ActPanelAck.activity_id)
  return _internal_activity_id();
}
inline void ActPanelAck::_internal_set_activity_id(int32_t value) {
  
  activity_id_ = value;
}
inline void ActPanelAck::set_activity_id(int32_t value) {
  _internal_set_activity_id(value);
  // @@protoc_insertion_point(field_set:cproto.ActPanelAck.activity_id)
}

// string json_data = 2;
inline void ActPanelAck::clear_json_data() {
  json_data_.ClearToEmpty();
}
inline const std::string& ActPanelAck::json_data() const {
  // @@protoc_insertion_point(field_get:cproto.ActPanelAck.json_data)
  return _internal_json_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActPanelAck::set_json_data(ArgT0&& arg0, ArgT... args) {
 
 json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cproto.ActPanelAck.json_data)
}
inline std::string* ActPanelAck::mutable_json_data() {
  std::string* _s = _internal_mutable_json_data();
  // @@protoc_insertion_point(field_mutable:cproto.ActPanelAck.json_data)
  return _s;
}
inline const std::string& ActPanelAck::_internal_json_data() const {
  return json_data_.Get();
}
inline void ActPanelAck::_internal_set_json_data(const std::string& value) {
  
  json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ActPanelAck::_internal_mutable_json_data() {
  
  return json_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ActPanelAck::release_json_data() {
  // @@protoc_insertion_point(field_release:cproto.ActPanelAck.json_data)
  return json_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ActPanelAck::set_allocated_json_data(std::string* json_data) {
  if (json_data != nullptr) {
    
  } else {
    
  }
  json_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), json_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (json_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    json_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cproto.ActPanelAck.json_data)
}

// -------------------------------------------------------------------

// ActRewardReq

// int32 activity_id = 1;
inline void ActRewardReq::clear_activity_id() {
  activity_id_ = 0;
}
inline int32_t ActRewardReq::_internal_activity_id() const {
  return activity_id_;
}
inline int32_t ActRewardReq::activity_id() const {
  // @@protoc_insertion_point(field_get:cproto.ActRewardReq.activity_id)
  return _internal_activity_id();
}
inline void ActRewardReq::_internal_set_activity_id(int32_t value) {
  
  activity_id_ = value;
}
inline void ActRewardReq::set_activity_id(int32_t value) {
  _internal_set_activity_id(value);
  // @@protoc_insertion_point(field_set:cproto.ActRewardReq.activity_id)
}

// string json_data = 2;
inline void ActRewardReq::clear_json_data() {
  json_data_.ClearToEmpty();
}
inline const std::string& ActRewardReq::json_data() const {
  // @@protoc_insertion_point(field_get:cproto.ActRewardReq.json_data)
  return _internal_json_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActRewardReq::set_json_data(ArgT0&& arg0, ArgT... args) {
 
 json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cproto.ActRewardReq.json_data)
}
inline std::string* ActRewardReq::mutable_json_data() {
  std::string* _s = _internal_mutable_json_data();
  // @@protoc_insertion_point(field_mutable:cproto.ActRewardReq.json_data)
  return _s;
}
inline const std::string& ActRewardReq::_internal_json_data() const {
  return json_data_.Get();
}
inline void ActRewardReq::_internal_set_json_data(const std::string& value) {
  
  json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ActRewardReq::_internal_mutable_json_data() {
  
  return json_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ActRewardReq::release_json_data() {
  // @@protoc_insertion_point(field_release:cproto.ActRewardReq.json_data)
  return json_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ActRewardReq::set_allocated_json_data(std::string* json_data) {
  if (json_data != nullptr) {
    
  } else {
    
  }
  json_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), json_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (json_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    json_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cproto.ActRewardReq.json_data)
}

// -------------------------------------------------------------------

// ActRewardAck

// int32 activity_id = 1;
inline void ActRewardAck::clear_activity_id() {
  activity_id_ = 0;
}
inline int32_t ActRewardAck::_internal_activity_id() const {
  return activity_id_;
}
inline int32_t ActRewardAck::activity_id() const {
  // @@protoc_insertion_point(field_get:cproto.ActRewardAck.activity_id)
  return _internal_activity_id();
}
inline void ActRewardAck::_internal_set_activity_id(int32_t value) {
  
  activity_id_ = value;
}
inline void ActRewardAck::set_activity_id(int32_t value) {
  _internal_set_activity_id(value);
  // @@protoc_insertion_point(field_set:cproto.ActRewardAck.activity_id)
}

// string json_data = 2;
inline void ActRewardAck::clear_json_data() {
  json_data_.ClearToEmpty();
}
inline const std::string& ActRewardAck::json_data() const {
  // @@protoc_insertion_point(field_get:cproto.ActRewardAck.json_data)
  return _internal_json_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActRewardAck::set_json_data(ArgT0&& arg0, ArgT... args) {
 
 json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cproto.ActRewardAck.json_data)
}
inline std::string* ActRewardAck::mutable_json_data() {
  std::string* _s = _internal_mutable_json_data();
  // @@protoc_insertion_point(field_mutable:cproto.ActRewardAck.json_data)
  return _s;
}
inline const std::string& ActRewardAck::_internal_json_data() const {
  return json_data_.Get();
}
inline void ActRewardAck::_internal_set_json_data(const std::string& value) {
  
  json_data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ActRewardAck::_internal_mutable_json_data() {
  
  return json_data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ActRewardAck::release_json_data() {
  // @@protoc_insertion_point(field_release:cproto.ActRewardAck.json_data)
  return json_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ActRewardAck::set_allocated_json_data(std::string* json_data) {
  if (json_data != nullptr) {
    
  } else {
    
  }
  json_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), json_data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (json_data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    json_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cproto.ActRewardAck.json_data)
}

// -------------------------------------------------------------------

// ActBrief

// int32 activity_id = 1;
inline void ActBrief::clear_activity_id() {
  activity_id_ = 0;
}
inline int32_t ActBrief::_internal_activity_id() const {
  return activity_id_;
}
inline int32_t ActBrief::activity_id() const {
  // @@protoc_insertion_point(field_get:cproto.ActBrief.activity_id)
  return _internal_activity_id();
}
inline void ActBrief::_internal_set_activity_id(int32_t value) {
  
  activity_id_ = value;
}
inline void ActBrief::set_activity_id(int32_t value) {
  _internal_set_activity_id(value);
  // @@protoc_insertion_point(field_set:cproto.ActBrief.activity_id)
}

// string name = 2;
inline void ActBrief::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& ActBrief::name() const {
  // @@protoc_insertion_point(field_get:cproto.ActBrief.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActBrief::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cproto.ActBrief.name)
}
inline std::string* ActBrief::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:cproto.ActBrief.name)
  return _s;
}
inline const std::string& ActBrief::_internal_name() const {
  return name_.Get();
}
inline void ActBrief::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ActBrief::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ActBrief::release_name() {
  // @@protoc_insertion_point(field_release:cproto.ActBrief.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ActBrief::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cproto.ActBrief.name)
}

// int32 status = 3;
inline void ActBrief::clear_status() {
  status_ = 0;
}
inline int32_t ActBrief::_internal_status() const {
  return status_;
}
inline int32_t ActBrief::status() const {
  // @@protoc_insertion_point(field_get:cproto.ActBrief.status)
  return _internal_status();
}
inline void ActBrief::_internal_set_status(int32_t value) {
  
  status_ = value;
}
inline void ActBrief::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:cproto.ActBrief.status)
}

// int64 end_ts = 4;
inline void ActBrief::clear_end_ts() {
  end_ts_ = int64_t{0};
}
inline int64_t ActBrief::_internal_end_ts() const {
  return end_ts_;
}
inline int64_t ActBrief::end_ts() const {
  // @@protoc_insertion_point(field_get:cproto.ActBrief.end_ts)
  return _internal_end_ts();
}
inline void ActBrief::_internal_set_end_ts(int64_t value) {
  
  end_ts_ = value;
}
inline void ActBrief::set_end_ts(int64_t value) {
  _internal_set_end_ts(value);
  // @@protoc_insertion_point(field_set:cproto.ActBrief.end_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cproto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_activity_2eproto
