// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.3
// source: hzxl.proto

package pbhzxl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HZXLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *anypb.Any             `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HZXLReq) Reset() {
	*x = HZXLReq{}
	mi := &file_hzxl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HZXLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HZXLReq) ProtoMessage() {}

func (x *HZXLReq) ProtoReflect() protoreflect.Message {
	mi := &file_hzxl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HZXLReq.ProtoReflect.Descriptor instead.
func (*HZXLReq) Descriptor() ([]byte, []int) {
	return file_hzxl_proto_rawDescGZIP(), []int{0}
}

func (x *HZXLReq) GetReq() *anypb.Any {
	if x != nil {
		return x.Req
	}
	return nil
}

type HZXLAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *anypb.Any             `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HZXLAck) Reset() {
	*x = HZXLAck{}
	mi := &file_hzxl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HZXLAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HZXLAck) ProtoMessage() {}

func (x *HZXLAck) ProtoReflect() protoreflect.Message {
	mi := &file_hzxl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HZXLAck.ProtoReflect.Descriptor instead.
func (*HZXLAck) Descriptor() ([]byte, []int) {
	return file_hzxl_proto_rawDescGZIP(), []int{1}
}

func (x *HZXLAck) GetAck() *anypb.Any {
	if x != nil {
		return x.Ack
	}
	return nil
}

var File_hzxl_proto protoreflect.FileDescriptor

const file_hzxl_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hzxl.proto\x12\x06pbhzxl\x1a\x19google/protobuf/any.proto\"1\n" +
	"\aHZXLReq\x12&\n" +
	"\x03req\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03req\"1\n" +
	"\aHZXLAck\x12&\n" +
	"\x03ack\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03ackB\tZ\a/pbhzxlb\x06proto3"

var (
	file_hzxl_proto_rawDescOnce sync.Once
	file_hzxl_proto_rawDescData []byte
)

func file_hzxl_proto_rawDescGZIP() []byte {
	file_hzxl_proto_rawDescOnce.Do(func() {
		file_hzxl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hzxl_proto_rawDesc), len(file_hzxl_proto_rawDesc)))
	})
	return file_hzxl_proto_rawDescData
}

var file_hzxl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hzxl_proto_goTypes = []any{
	(*HZXLReq)(nil),   // 0: pbhzxl.HZXLReq
	(*HZXLAck)(nil),   // 1: pbhzxl.HZXLAck
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_hzxl_proto_depIdxs = []int32{
	2, // 0: pbhzxl.HZXLReq.req:type_name -> google.protobuf.Any
	2, // 1: pbhzxl.HZXLAck.ack:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hzxl_proto_init() }
func file_hzxl_proto_init() {
	if File_hzxl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hzxl_proto_rawDesc), len(file_hzxl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hzxl_proto_goTypes,
		DependencyIndexes: file_hzxl_proto_depIdxs,
		MessageInfos:      file_hzxl_proto_msgTypes,
	}.Build()
	File_hzxl_proto = out.File
	file_hzxl_proto_goTypes = nil
	file_hzxl_proto_depIdxs = nil
}
